// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discover_trending.sql

package db

import (
	"context"
	"strings"
)

const deleteDiscoverTrendingSignalsForRepo = `-- name: DeleteDiscoverTrendingSignalsForRepo :exec
DELETE FROM discover_trending_signals WHERE repo_did = ?
`

func (q *Queries) DeleteDiscoverTrendingSignalsForRepo(ctx context.Context, repoDid string) error {
	_, err := q.db.ExecContext(ctx, deleteDiscoverTrendingSignalsForRepo, repoDid)
	return err
}

const deleteDiscoverTrendingSourceCounts = `-- name: DeleteDiscoverTrendingSourceCounts :exec
DELETE FROM discover_trending_source_counts
`

func (q *Queries) DeleteDiscoverTrendingSourceCounts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteDiscoverTrendingSourceCounts)
	return err
}

const getDiscoverBatchState = `-- name: GetDiscoverBatchState :one
SELECT id, last_run_at FROM discover_batch_state WHERE id = 1
`

func (q *Queries) GetDiscoverBatchState(ctx context.Context) (DiscoverBatchState, error) {
	row := q.db.QueryRowContext(ctx, getDiscoverBatchState)
	var i DiscoverBatchState
	err := row.Scan(&i.ID, &i.LastRunAt)
	return i, err
}

const getDiscoverTrendingSignalTitle = `-- name: GetDiscoverTrendingSignalTitle :one
SELECT title, site_url FROM discover_trending_signals
WHERE source_key = ? AND title IS NOT NULL AND title != ''
LIMIT 1
`

type GetDiscoverTrendingSignalTitleRow struct {
	Title   *string `json:"title"`
	SiteUrl *string `json:"site_url"`
}

// Backfills a reaction-only rss candidate's title/siteUrl (SPEC <discovery>);
// deliberately not gated by the min-3-repo trending bar used in
// ListDiscoverTrendingSignalsAboveBar, since a title only needs one
// contributing repo, unlike a trending card.
func (q *Queries) GetDiscoverTrendingSignalTitle(ctx context.Context, sourceKey string) (GetDiscoverTrendingSignalTitleRow, error) {
	row := q.db.QueryRowContext(ctx, getDiscoverTrendingSignalTitle, sourceKey)
	var i GetDiscoverTrendingSignalTitleRow
	err := row.Scan(&i.Title, &i.SiteUrl)
	return i, err
}

const insertDiscoverTrendingSignal = `-- name: InsertDiscoverTrendingSignal :exec
INSERT INTO discover_trending_signals (
    repo_did, source_key, kind, title, site_url, signal_kind, signal_at, fetched_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertDiscoverTrendingSignalParams struct {
	RepoDid    string  `json:"repo_did"`
	SourceKey  string  `json:"source_key"`
	Kind       string  `json:"kind"`
	Title      *string `json:"title"`
	SiteUrl    *string `json:"site_url"`
	SignalKind string  `json:"signal_kind"`
	SignalAt   *string `json:"signal_at"`
	FetchedAt  string  `json:"fetched_at"`
}

func (q *Queries) InsertDiscoverTrendingSignal(ctx context.Context, arg InsertDiscoverTrendingSignalParams) error {
	_, err := q.db.ExecContext(ctx, insertDiscoverTrendingSignal,
		arg.RepoDid,
		arg.SourceKey,
		arg.Kind,
		arg.Title,
		arg.SiteUrl,
		arg.SignalKind,
		arg.SignalAt,
		arg.FetchedAt,
	)
	return err
}

const listDiscoverTrendingSignalTitles = `-- name: ListDiscoverTrendingSignalTitles :many
SELECT source_key, title, site_url FROM discover_trending_signals
WHERE source_key IN (/*SLICE:source_keys*/?)
  AND title IS NOT NULL AND title != ''
ORDER BY source_key
`

type ListDiscoverTrendingSignalTitlesRow struct {
	SourceKey string  `json:"source_key"`
	Title     *string `json:"title"`
	SiteUrl   *string `json:"site_url"`
}

// Batched form of GetDiscoverTrendingSignalTitle for backfilling a whole page
// of reaction-only rss candidates. Returns every titled row for the requested
// keys; the caller keeps the first row per source_key, so ordering only has to
// group the keys together. Same deliberate absence of the min-repo trending
// bar: a title needs one contributing repo, unlike a trending card.
func (q *Queries) ListDiscoverTrendingSignalTitles(ctx context.Context, sourceKeys []string) ([]ListDiscoverTrendingSignalTitlesRow, error) {
	query := listDiscoverTrendingSignalTitles
	var queryParams []interface{}
	if len(sourceKeys) > 0 {
		for _, v := range sourceKeys {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:source_keys*/?", strings.Repeat(",?", len(sourceKeys))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:source_keys*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDiscoverTrendingSignalTitlesRow
	for rows.Next() {
		var i ListDiscoverTrendingSignalTitlesRow
		if err := rows.Scan(&i.SourceKey, &i.Title, &i.SiteUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoverTrendingSignals = `-- name: ListDiscoverTrendingSignals :many
SELECT repo_did, source_key, kind, title, site_url, signal_kind, signal_at, fetched_at
FROM discover_trending_signals
`

// Whole-table read; kept for callers that genuinely need every row (see
// internal/discoverbatch's write-path tests). The trending handler reads
// ListDiscoverTrendingSignalsAboveBar instead (see that query's comment).
func (q *Queries) ListDiscoverTrendingSignals(ctx context.Context) ([]DiscoverTrendingSignal, error) {
	rows, err := q.db.QueryContext(ctx, listDiscoverTrendingSignals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoverTrendingSignal
	for rows.Next() {
		var i DiscoverTrendingSignal
		if err := rows.Scan(
			&i.RepoDid,
			&i.SourceKey,
			&i.Kind,
			&i.Title,
			&i.SiteUrl,
			&i.SignalKind,
			&i.SignalAt,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoverTrendingSignalsAboveBar = `-- name: ListDiscoverTrendingSignalsAboveBar :many
SELECT s.repo_did, s.source_key, s.kind, s.title, s.site_url, s.signal_kind, s.signal_at, s.fetched_at
FROM discover_trending_signals s
JOIN discover_trending_source_counts c ON c.source_key = s.source_key
WHERE c.distinct_repos >= CAST(?1 AS BIGINT)
`

// Bounds the trending-sources read to source_keys with signals from at
// least min_distinct_repos distinct repos (SPEC <discovery> "Quality bar")
// instead of loading the whole network table; grouping/scoring for the
// surviving candidates still happens in Go via RankTrending, which keeps
// its own MinDistinctRepos check as defense in depth. The bar reads the
// counts table the batch rebuilds, so it costs a keyed lookup per row
// rather than a correlated COUNT(DISTINCT) over the whole signals table.
func (q *Queries) ListDiscoverTrendingSignalsAboveBar(ctx context.Context, minDistinctRepos int64) ([]DiscoverTrendingSignal, error) {
	rows, err := q.db.QueryContext(ctx, listDiscoverTrendingSignalsAboveBar, minDistinctRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoverTrendingSignal
	for rows.Next() {
		var i DiscoverTrendingSignal
		if err := rows.Scan(
			&i.RepoDid,
			&i.SourceKey,
			&i.Kind,
			&i.Title,
			&i.SiteUrl,
			&i.SignalKind,
			&i.SignalAt,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoverTrendingSignalsForEligibleSubjects = `-- name: ListDiscoverTrendingSignalsForEligibleSubjects :many
SELECT s.repo_did, s.source_key, s.kind, s.title, s.site_url, s.signal_kind, s.signal_at, s.fetched_at
FROM discover_trending_signals s
JOIN discover_trending_follow_counts c ON c.subject_did = s.repo_did
WHERE s.signal_kind != 'save'
AND c.distinct_repos >= CAST(?1 AS BIGINT)
`

// Bounds the People trending eligibility read (SPEC <discovery> People
// "Eligibility") to repos that are themselves subject_dids clearing the
// follower quality bar, instead of loading the whole signals table to test
// each candidate's reader-network presence. Same counts-table join as
// ListDiscoverTrendingSignalsAboveBar, against the follower counts.
// signal_kind != 'save' is the save-privacy invariant: a save-only subject
// must never clear eligibility (SPEC <discovery> People "Eligibility":
// "Saves don't confer eligibility").
func (q *Queries) ListDiscoverTrendingSignalsForEligibleSubjects(ctx context.Context, minDistinctRepos int64) ([]DiscoverTrendingSignal, error) {
	rows, err := q.db.QueryContext(ctx, listDiscoverTrendingSignalsForEligibleSubjects, minDistinctRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoverTrendingSignal
	for rows.Next() {
		var i DiscoverTrendingSignal
		if err := rows.Scan(
			&i.RepoDid,
			&i.SourceKey,
			&i.Kind,
			&i.Title,
			&i.SiteUrl,
			&i.SignalKind,
			&i.SignalAt,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rebuildDiscoverTrendingSourceCounts = `-- name: RebuildDiscoverTrendingSourceCounts :exec
INSERT INTO discover_trending_source_counts (source_key, distinct_repos)
SELECT source_key, COUNT(DISTINCT repo_did)
FROM discover_trending_signals
GROUP BY source_key
`

// Paired with DeleteDiscoverTrendingSourceCounts inside one transaction: the
// aggregation ListDiscoverTrendingSignalsAboveBar used to run per read, hoisted
// to once per batch pass.
func (q *Queries) RebuildDiscoverTrendingSourceCounts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, rebuildDiscoverTrendingSourceCounts)
	return err
}

const upsertDiscoverBatchState = `-- name: UpsertDiscoverBatchState :exec
INSERT INTO discover_batch_state (id, last_run_at) VALUES (1, ?)
ON CONFLICT (id) DO UPDATE SET last_run_at = excluded.last_run_at
`

func (q *Queries) UpsertDiscoverBatchState(ctx context.Context, lastRunAt string) error {
	_, err := q.db.ExecContext(ctx, upsertDiscoverBatchState, lastRunAt)
	return err
}
