// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discover.sql

package db

import (
	"context"
)

const deleteDiscoverCrawlAdjacentFollows = `-- name: DeleteDiscoverCrawlAdjacentFollows :exec
DELETE FROM discover_crawl_adjacent_follows WHERE did = ?
`

func (q *Queries) DeleteDiscoverCrawlAdjacentFollows(ctx context.Context, did string) error {
	_, err := q.db.ExecContext(ctx, deleteDiscoverCrawlAdjacentFollows, did)
	return err
}

const deleteDiscoverCrawlAuthored = `-- name: DeleteDiscoverCrawlAuthored :exec
DELETE FROM discover_crawl_authored WHERE followed_did = ?
`

func (q *Queries) DeleteDiscoverCrawlAuthored(ctx context.Context, followedDid string) error {
	_, err := q.db.ExecContext(ctx, deleteDiscoverCrawlAuthored, followedDid)
	return err
}

const deleteDiscoverCrawlFollows = `-- name: DeleteDiscoverCrawlFollows :exec
DELETE FROM discover_crawl_follows WHERE followed_did = ?
`

func (q *Queries) DeleteDiscoverCrawlFollows(ctx context.Context, followedDid string) error {
	_, err := q.db.ExecContext(ctx, deleteDiscoverCrawlFollows, followedDid)
	return err
}

const deleteDiscoverCrawlOwnForeignSubscriptions = `-- name: DeleteDiscoverCrawlOwnForeignSubscriptions :exec
DELETE FROM discover_crawl_own_foreign_subscriptions WHERE did = ?
`

func (q *Queries) DeleteDiscoverCrawlOwnForeignSubscriptions(ctx context.Context, did string) error {
	_, err := q.db.ExecContext(ctx, deleteDiscoverCrawlOwnForeignSubscriptions, did)
	return err
}

const deleteDiscoverCrawlShares = `-- name: DeleteDiscoverCrawlShares :exec
DELETE FROM discover_crawl_shares WHERE followed_did = ?
`

func (q *Queries) DeleteDiscoverCrawlShares(ctx context.Context, followedDid string) error {
	_, err := q.db.ExecContext(ctx, deleteDiscoverCrawlShares, followedDid)
	return err
}

const deleteDiscoverCrawlSubscriptions = `-- name: DeleteDiscoverCrawlSubscriptions :exec
DELETE FROM discover_crawl_subscriptions WHERE followed_did = ?
`

func (q *Queries) DeleteDiscoverCrawlSubscriptions(ctx context.Context, followedDid string) error {
	_, err := q.db.ExecContext(ctx, deleteDiscoverCrawlSubscriptions, followedDid)
	return err
}

const getDiscoverCrawlAdjacentState = `-- name: GetDiscoverCrawlAdjacentState :one
SELECT did, fetched_at FROM discover_crawl_adjacent_state WHERE did = ?
`

func (q *Queries) GetDiscoverCrawlAdjacentState(ctx context.Context, did string) (DiscoverCrawlAdjacentState, error) {
	row := q.db.QueryRowContext(ctx, getDiscoverCrawlAdjacentState, did)
	var i DiscoverCrawlAdjacentState
	err := row.Scan(&i.Did, &i.FetchedAt)
	return i, err
}

const getDiscoverCrawlAuthoredState = `-- name: GetDiscoverCrawlAuthoredState :one
SELECT followed_did, fetched_at FROM discover_crawl_authored_state WHERE followed_did = ?
`

func (q *Queries) GetDiscoverCrawlAuthoredState(ctx context.Context, followedDid string) (DiscoverCrawlAuthoredState, error) {
	row := q.db.QueryRowContext(ctx, getDiscoverCrawlAuthoredState, followedDid)
	var i DiscoverCrawlAuthoredState
	err := row.Scan(&i.FollowedDid, &i.FetchedAt)
	return i, err
}

const getDiscoverCrawlFollowState = `-- name: GetDiscoverCrawlFollowState :one
SELECT followed_did, fetched_at FROM discover_crawl_follow_state WHERE followed_did = ?
`

func (q *Queries) GetDiscoverCrawlFollowState(ctx context.Context, followedDid string) (DiscoverCrawlFollowState, error) {
	row := q.db.QueryRowContext(ctx, getDiscoverCrawlFollowState, followedDid)
	var i DiscoverCrawlFollowState
	err := row.Scan(&i.FollowedDid, &i.FetchedAt)
	return i, err
}

const getDiscoverCrawlOwnForeignState = `-- name: GetDiscoverCrawlOwnForeignState :one
SELECT did, fetched_at FROM discover_crawl_own_foreign_state WHERE did = ?
`

func (q *Queries) GetDiscoverCrawlOwnForeignState(ctx context.Context, did string) (DiscoverCrawlOwnForeignState, error) {
	row := q.db.QueryRowContext(ctx, getDiscoverCrawlOwnForeignState, did)
	var i DiscoverCrawlOwnForeignState
	err := row.Scan(&i.Did, &i.FetchedAt)
	return i, err
}

const getDiscoverCrawlShareState = `-- name: GetDiscoverCrawlShareState :one
SELECT followed_did, fetched_at FROM discover_crawl_share_state WHERE followed_did = ?
`

func (q *Queries) GetDiscoverCrawlShareState(ctx context.Context, followedDid string) (DiscoverCrawlShareState, error) {
	row := q.db.QueryRowContext(ctx, getDiscoverCrawlShareState, followedDid)
	var i DiscoverCrawlShareState
	err := row.Scan(&i.FollowedDid, &i.FetchedAt)
	return i, err
}

const getDiscoverCrawlState = `-- name: GetDiscoverCrawlState :one
SELECT followed_did, fetched_at FROM discover_crawl_state WHERE followed_did = ?
`

func (q *Queries) GetDiscoverCrawlState(ctx context.Context, followedDid string) (DiscoverCrawlState, error) {
	row := q.db.QueryRowContext(ctx, getDiscoverCrawlState, followedDid)
	var i DiscoverCrawlState
	err := row.Scan(&i.FollowedDid, &i.FetchedAt)
	return i, err
}

const getDiscoverCrawlSubscriptionSiteURLByKey = `-- name: GetDiscoverCrawlSubscriptionSiteURLByKey :one
SELECT site_url FROM discover_crawl_subscriptions WHERE canonical_key = ? AND site_url IS NOT NULL AND site_url != '' LIMIT 1
`

// Site-URL fallback for on-demand favicon discovery when the resolution cache misses.
func (q *Queries) GetDiscoverCrawlSubscriptionSiteURLByKey(ctx context.Context, canonicalKey string) (*string, error) {
	row := q.db.QueryRowContext(ctx, getDiscoverCrawlSubscriptionSiteURLByKey, canonicalKey)
	var site_url *string
	err := row.Scan(&site_url)
	return site_url, err
}

const insertDiscoverCrawlAdjacentFollow = `-- name: InsertDiscoverCrawlAdjacentFollow :exec
INSERT INTO discover_crawl_adjacent_follows (did, subject_did, network, fetched_at) VALUES (?, ?, ?, ?)
`

type InsertDiscoverCrawlAdjacentFollowParams struct {
	Did        string `json:"did"`
	SubjectDid string `json:"subject_did"`
	Network    string `json:"network"`
	FetchedAt  string `json:"fetched_at"`
}

func (q *Queries) InsertDiscoverCrawlAdjacentFollow(ctx context.Context, arg InsertDiscoverCrawlAdjacentFollowParams) error {
	_, err := q.db.ExecContext(ctx, insertDiscoverCrawlAdjacentFollow,
		arg.Did,
		arg.SubjectDid,
		arg.Network,
		arg.FetchedAt,
	)
	return err
}

const insertDiscoverCrawlAuthored = `-- name: InsertDiscoverCrawlAuthored :exec
INSERT INTO discover_crawl_authored (
    followed_did, canonical_key, kind, title, site_url, last_published_at, fetched_at, verification
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertDiscoverCrawlAuthoredParams struct {
	FollowedDid     string  `json:"followed_did"`
	CanonicalKey    string  `json:"canonical_key"`
	Kind            string  `json:"kind"`
	Title           *string `json:"title"`
	SiteUrl         *string `json:"site_url"`
	LastPublishedAt *string `json:"last_published_at"`
	FetchedAt       string  `json:"fetched_at"`
	Verification    string  `json:"verification"`
}

func (q *Queries) InsertDiscoverCrawlAuthored(ctx context.Context, arg InsertDiscoverCrawlAuthoredParams) error {
	_, err := q.db.ExecContext(ctx, insertDiscoverCrawlAuthored,
		arg.FollowedDid,
		arg.CanonicalKey,
		arg.Kind,
		arg.Title,
		arg.SiteUrl,
		arg.LastPublishedAt,
		arg.FetchedAt,
		arg.Verification,
	)
	return err
}

const insertDiscoverCrawlFollow = `-- name: InsertDiscoverCrawlFollow :exec
INSERT INTO discover_crawl_follows (followed_did, subject_did, fetched_at) VALUES (?, ?, ?)
`

type InsertDiscoverCrawlFollowParams struct {
	FollowedDid string `json:"followed_did"`
	SubjectDid  string `json:"subject_did"`
	FetchedAt   string `json:"fetched_at"`
}

func (q *Queries) InsertDiscoverCrawlFollow(ctx context.Context, arg InsertDiscoverCrawlFollowParams) error {
	_, err := q.db.ExecContext(ctx, insertDiscoverCrawlFollow, arg.FollowedDid, arg.SubjectDid, arg.FetchedAt)
	return err
}

const insertDiscoverCrawlOwnForeignSubscription = `-- name: InsertDiscoverCrawlOwnForeignSubscription :exec
INSERT INTO discover_crawl_own_foreign_subscriptions (
    did, canonical_key, kind, app, title, site_url, created_at, fetched_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertDiscoverCrawlOwnForeignSubscriptionParams struct {
	Did          string  `json:"did"`
	CanonicalKey string  `json:"canonical_key"`
	Kind         string  `json:"kind"`
	App          string  `json:"app"`
	Title        *string `json:"title"`
	SiteUrl      *string `json:"site_url"`
	CreatedAt    *string `json:"created_at"`
	FetchedAt    string  `json:"fetched_at"`
}

func (q *Queries) InsertDiscoverCrawlOwnForeignSubscription(ctx context.Context, arg InsertDiscoverCrawlOwnForeignSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, insertDiscoverCrawlOwnForeignSubscription,
		arg.Did,
		arg.CanonicalKey,
		arg.Kind,
		arg.App,
		arg.Title,
		arg.SiteUrl,
		arg.CreatedAt,
		arg.FetchedAt,
	)
	return err
}

const insertDiscoverCrawlShare = `-- name: InsertDiscoverCrawlShare :exec
INSERT INTO discover_crawl_shares (
    followed_did, dedupe_key, kind, item_url, document, feed_url, comment, created_at, fetched_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertDiscoverCrawlShareParams struct {
	FollowedDid string  `json:"followed_did"`
	DedupeKey   string  `json:"dedupe_key"`
	Kind        string  `json:"kind"`
	ItemUrl     *string `json:"item_url"`
	Document    *string `json:"document"`
	FeedUrl     *string `json:"feed_url"`
	Comment     *string `json:"comment"`
	CreatedAt   string  `json:"created_at"`
	FetchedAt   string  `json:"fetched_at"`
}

func (q *Queries) InsertDiscoverCrawlShare(ctx context.Context, arg InsertDiscoverCrawlShareParams) error {
	_, err := q.db.ExecContext(ctx, insertDiscoverCrawlShare,
		arg.FollowedDid,
		arg.DedupeKey,
		arg.Kind,
		arg.ItemUrl,
		arg.Document,
		arg.FeedUrl,
		arg.Comment,
		arg.CreatedAt,
		arg.FetchedAt,
	)
	return err
}

const insertDiscoverCrawlSubscription = `-- name: InsertDiscoverCrawlSubscription :exec
INSERT INTO discover_crawl_subscriptions (
    followed_did, canonical_key, kind, title, site_url, fetched_at, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertDiscoverCrawlSubscriptionParams struct {
	FollowedDid  string  `json:"followed_did"`
	CanonicalKey string  `json:"canonical_key"`
	Kind         string  `json:"kind"`
	Title        *string `json:"title"`
	SiteUrl      *string `json:"site_url"`
	FetchedAt    string  `json:"fetched_at"`
	CreatedAt    *string `json:"created_at"`
}

func (q *Queries) InsertDiscoverCrawlSubscription(ctx context.Context, arg InsertDiscoverCrawlSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, insertDiscoverCrawlSubscription,
		arg.FollowedDid,
		arg.CanonicalKey,
		arg.Kind,
		arg.Title,
		arg.SiteUrl,
		arg.FetchedAt,
		arg.CreatedAt,
	)
	return err
}

const listDiscoverCrawlAdjacentFollows = `-- name: ListDiscoverCrawlAdjacentFollows :many
SELECT did, subject_did, network, fetched_at
FROM discover_crawl_adjacent_follows WHERE did = ?
`

func (q *Queries) ListDiscoverCrawlAdjacentFollows(ctx context.Context, did string) ([]DiscoverCrawlAdjacentFollow, error) {
	rows, err := q.db.QueryContext(ctx, listDiscoverCrawlAdjacentFollows, did)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoverCrawlAdjacentFollow
	for rows.Next() {
		var i DiscoverCrawlAdjacentFollow
		if err := rows.Scan(
			&i.Did,
			&i.SubjectDid,
			&i.Network,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoverCrawlAuthored = `-- name: ListDiscoverCrawlAuthored :many
SELECT followed_did, canonical_key, kind, title, site_url, last_published_at, fetched_at, verification
FROM discover_crawl_authored WHERE followed_did = ?
`

// Returns every cached outcome, verified and not; callers filter to verified-only in Go (authored_store.go), keeping this query free to surface all outcomes for a future retry policy.
func (q *Queries) ListDiscoverCrawlAuthored(ctx context.Context, followedDid string) ([]DiscoverCrawlAuthored, error) {
	rows, err := q.db.QueryContext(ctx, listDiscoverCrawlAuthored, followedDid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoverCrawlAuthored
	for rows.Next() {
		var i DiscoverCrawlAuthored
		if err := rows.Scan(
			&i.FollowedDid,
			&i.CanonicalKey,
			&i.Kind,
			&i.Title,
			&i.SiteUrl,
			&i.LastPublishedAt,
			&i.FetchedAt,
			&i.Verification,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoverCrawlFollows = `-- name: ListDiscoverCrawlFollows :many
SELECT followed_did, subject_did, fetched_at
FROM discover_crawl_follows WHERE followed_did = ?
`

func (q *Queries) ListDiscoverCrawlFollows(ctx context.Context, followedDid string) ([]DiscoverCrawlFollow, error) {
	rows, err := q.db.QueryContext(ctx, listDiscoverCrawlFollows, followedDid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoverCrawlFollow
	for rows.Next() {
		var i DiscoverCrawlFollow
		if err := rows.Scan(&i.FollowedDid, &i.SubjectDid, &i.FetchedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoverCrawlOwnForeignSubscriptions = `-- name: ListDiscoverCrawlOwnForeignSubscriptions :many
SELECT did, canonical_key, kind, app, title, site_url, created_at, fetched_at
FROM discover_crawl_own_foreign_subscriptions WHERE did = ?
`

// Column order matches the table's physical layout so sqlc reuses the
// DiscoverCrawlOwnForeignSubscription model instead of minting a one-off row type.
func (q *Queries) ListDiscoverCrawlOwnForeignSubscriptions(ctx context.Context, did string) ([]DiscoverCrawlOwnForeignSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listDiscoverCrawlOwnForeignSubscriptions, did)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoverCrawlOwnForeignSubscription
	for rows.Next() {
		var i DiscoverCrawlOwnForeignSubscription
		if err := rows.Scan(
			&i.Did,
			&i.CanonicalKey,
			&i.Kind,
			&i.App,
			&i.Title,
			&i.SiteUrl,
			&i.CreatedAt,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoverCrawlShares = `-- name: ListDiscoverCrawlShares :many
SELECT followed_did, dedupe_key, kind, item_url, document, feed_url, comment, created_at, fetched_at
FROM discover_crawl_shares WHERE followed_did = ?
`

func (q *Queries) ListDiscoverCrawlShares(ctx context.Context, followedDid string) ([]DiscoverCrawlShare, error) {
	rows, err := q.db.QueryContext(ctx, listDiscoverCrawlShares, followedDid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoverCrawlShare
	for rows.Next() {
		var i DiscoverCrawlShare
		if err := rows.Scan(
			&i.FollowedDid,
			&i.DedupeKey,
			&i.Kind,
			&i.ItemUrl,
			&i.Document,
			&i.FeedUrl,
			&i.Comment,
			&i.CreatedAt,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoverCrawlSubscriptions = `-- name: ListDiscoverCrawlSubscriptions :many
SELECT followed_did, canonical_key, kind, title, site_url, created_at, fetched_at
FROM discover_crawl_subscriptions WHERE followed_did = ?
`

// Column order matches the table's physical layout so sqlc reuses the
// DiscoverCrawlSubscription model instead of minting a one-off row type.
func (q *Queries) ListDiscoverCrawlSubscriptions(ctx context.Context, followedDid string) ([]DiscoverCrawlSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listDiscoverCrawlSubscriptions, followedDid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoverCrawlSubscription
	for rows.Next() {
		var i DiscoverCrawlSubscription
		if err := rows.Scan(
			&i.FollowedDid,
			&i.CanonicalKey,
			&i.Kind,
			&i.Title,
			&i.SiteUrl,
			&i.CreatedAt,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDiscoverCrawlAdjacentState = `-- name: UpsertDiscoverCrawlAdjacentState :exec
INSERT INTO discover_crawl_adjacent_state (did, fetched_at) VALUES (?, ?)
ON CONFLICT (did) DO UPDATE SET fetched_at = excluded.fetched_at
`

type UpsertDiscoverCrawlAdjacentStateParams struct {
	Did       string `json:"did"`
	FetchedAt string `json:"fetched_at"`
}

func (q *Queries) UpsertDiscoverCrawlAdjacentState(ctx context.Context, arg UpsertDiscoverCrawlAdjacentStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertDiscoverCrawlAdjacentState, arg.Did, arg.FetchedAt)
	return err
}

const upsertDiscoverCrawlAuthoredState = `-- name: UpsertDiscoverCrawlAuthoredState :exec
INSERT INTO discover_crawl_authored_state (followed_did, fetched_at) VALUES (?, ?)
ON CONFLICT (followed_did) DO UPDATE SET fetched_at = excluded.fetched_at
`

type UpsertDiscoverCrawlAuthoredStateParams struct {
	FollowedDid string `json:"followed_did"`
	FetchedAt   string `json:"fetched_at"`
}

func (q *Queries) UpsertDiscoverCrawlAuthoredState(ctx context.Context, arg UpsertDiscoverCrawlAuthoredStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertDiscoverCrawlAuthoredState, arg.FollowedDid, arg.FetchedAt)
	return err
}

const upsertDiscoverCrawlFollowState = `-- name: UpsertDiscoverCrawlFollowState :exec
INSERT INTO discover_crawl_follow_state (followed_did, fetched_at) VALUES (?, ?)
ON CONFLICT (followed_did) DO UPDATE SET fetched_at = excluded.fetched_at
`

type UpsertDiscoverCrawlFollowStateParams struct {
	FollowedDid string `json:"followed_did"`
	FetchedAt   string `json:"fetched_at"`
}

func (q *Queries) UpsertDiscoverCrawlFollowState(ctx context.Context, arg UpsertDiscoverCrawlFollowStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertDiscoverCrawlFollowState, arg.FollowedDid, arg.FetchedAt)
	return err
}

const upsertDiscoverCrawlOwnForeignState = `-- name: UpsertDiscoverCrawlOwnForeignState :exec
INSERT INTO discover_crawl_own_foreign_state (did, fetched_at) VALUES (?, ?)
ON CONFLICT (did) DO UPDATE SET fetched_at = excluded.fetched_at
`

type UpsertDiscoverCrawlOwnForeignStateParams struct {
	Did       string `json:"did"`
	FetchedAt string `json:"fetched_at"`
}

func (q *Queries) UpsertDiscoverCrawlOwnForeignState(ctx context.Context, arg UpsertDiscoverCrawlOwnForeignStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertDiscoverCrawlOwnForeignState, arg.Did, arg.FetchedAt)
	return err
}

const upsertDiscoverCrawlShareState = `-- name: UpsertDiscoverCrawlShareState :exec
INSERT INTO discover_crawl_share_state (followed_did, fetched_at) VALUES (?, ?)
ON CONFLICT (followed_did) DO UPDATE SET fetched_at = excluded.fetched_at
`

type UpsertDiscoverCrawlShareStateParams struct {
	FollowedDid string `json:"followed_did"`
	FetchedAt   string `json:"fetched_at"`
}

func (q *Queries) UpsertDiscoverCrawlShareState(ctx context.Context, arg UpsertDiscoverCrawlShareStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertDiscoverCrawlShareState, arg.FollowedDid, arg.FetchedAt)
	return err
}

const upsertDiscoverCrawlState = `-- name: UpsertDiscoverCrawlState :exec
INSERT INTO discover_crawl_state (followed_did, fetched_at) VALUES (?, ?)
ON CONFLICT (followed_did) DO UPDATE SET fetched_at = excluded.fetched_at
`

type UpsertDiscoverCrawlStateParams struct {
	FollowedDid string `json:"followed_did"`
	FetchedAt   string `json:"fetched_at"`
}

func (q *Queries) UpsertDiscoverCrawlState(ctx context.Context, arg UpsertDiscoverCrawlStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertDiscoverCrawlState, arg.FollowedDid, arg.FetchedAt)
	return err
}
