// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discover_trending_follows.sql

package db

import (
	"context"
)

const deleteDiscoverTrendingFollowCounts = `-- name: DeleteDiscoverTrendingFollowCounts :exec
DELETE FROM discover_trending_follow_counts
`

func (q *Queries) DeleteDiscoverTrendingFollowCounts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteDiscoverTrendingFollowCounts)
	return err
}

const deleteDiscoverTrendingFollowsForRepo = `-- name: DeleteDiscoverTrendingFollowsForRepo :exec
DELETE FROM discover_trending_follows WHERE repo_did = ?
`

func (q *Queries) DeleteDiscoverTrendingFollowsForRepo(ctx context.Context, repoDid string) error {
	_, err := q.db.ExecContext(ctx, deleteDiscoverTrendingFollowsForRepo, repoDid)
	return err
}

const insertDiscoverTrendingFollow = `-- name: InsertDiscoverTrendingFollow :exec
INSERT INTO discover_trending_follows (
    repo_did, subject_did, fetched_at
) VALUES (?, ?, ?)
`

type InsertDiscoverTrendingFollowParams struct {
	RepoDid    string `json:"repo_did"`
	SubjectDid string `json:"subject_did"`
	FetchedAt  string `json:"fetched_at"`
}

func (q *Queries) InsertDiscoverTrendingFollow(ctx context.Context, arg InsertDiscoverTrendingFollowParams) error {
	_, err := q.db.ExecContext(ctx, insertDiscoverTrendingFollow, arg.RepoDid, arg.SubjectDid, arg.FetchedAt)
	return err
}

const listDiscoverTrendingFollows = `-- name: ListDiscoverTrendingFollows :many
SELECT repo_did, subject_did, fetched_at
FROM discover_trending_follows
`

// Whole-table read; kept for callers that genuinely need every row (see
// internal/discoverbatch's write-path tests). The trending handler reads
// ListDiscoverTrendingFollowsAboveBar instead (see that query's comment).
func (q *Queries) ListDiscoverTrendingFollows(ctx context.Context) ([]DiscoverTrendingFollow, error) {
	rows, err := q.db.QueryContext(ctx, listDiscoverTrendingFollows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoverTrendingFollow
	for rows.Next() {
		var i DiscoverTrendingFollow
		if err := rows.Scan(&i.RepoDid, &i.SubjectDid, &i.FetchedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoverTrendingFollowsAboveBar = `-- name: ListDiscoverTrendingFollowsAboveBar :many
SELECT f.repo_did, f.subject_did, f.fetched_at
FROM discover_trending_follows f
JOIN discover_trending_follow_counts c ON c.subject_did = f.subject_did
WHERE c.distinct_repos >= CAST(?1 AS BIGINT)
`

// Bounds the trending-people read to subject_dids with followers from at
// least min_distinct_repos distinct repos (SPEC <discovery> People
// "Global/Trending": "same >=3-distinct-repos bar") instead of loading the
// whole network table; scoring for the surviving candidates still happens
// in Go via RankPeopleTrending, which keeps its own MinDistinctRepos check
// as defense in depth. The bar reads the counts table the batch rebuilds,
// so it costs a keyed lookup per row rather than a correlated
// COUNT(DISTINCT) over the whole follows table.
func (q *Queries) ListDiscoverTrendingFollowsAboveBar(ctx context.Context, minDistinctRepos int64) ([]DiscoverTrendingFollow, error) {
	rows, err := q.db.QueryContext(ctx, listDiscoverTrendingFollowsAboveBar, minDistinctRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoverTrendingFollow
	for rows.Next() {
		var i DiscoverTrendingFollow
		if err := rows.Scan(&i.RepoDid, &i.SubjectDid, &i.FetchedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rebuildDiscoverTrendingFollowCounts = `-- name: RebuildDiscoverTrendingFollowCounts :exec
INSERT INTO discover_trending_follow_counts (subject_did, distinct_repos)
SELECT subject_did, COUNT(DISTINCT repo_did)
FROM discover_trending_follows
GROUP BY subject_did
`

// Paired with DeleteDiscoverTrendingFollowCounts inside one transaction: the
// aggregation ListDiscoverTrendingFollowsAboveBar used to run per read, hoisted
// to once per batch pass.
func (q *Queries) RebuildDiscoverTrendingFollowCounts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, rebuildDiscoverTrendingFollowCounts)
	return err
}
