// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discover_source_posts.sql

package db

import (
	"context"
)

const deleteDiscoverSourcePosts = `-- name: DeleteDiscoverSourcePosts :exec
DELETE FROM discover_source_posts WHERE source_key = ?
`

func (q *Queries) DeleteDiscoverSourcePosts(ctx context.Context, sourceKey string) error {
	_, err := q.db.ExecContext(ctx, deleteDiscoverSourcePosts, sourceKey)
	return err
}

const getDiscoverSourceFaviconURL = `-- name: GetDiscoverSourceFaviconURL :one
SELECT favicon_url FROM discover_source_posts_state WHERE source_key = ?
`

// Fallback lookup for the favicon proxy when a candidate isn't in the feeds table yet (not subscribed).
func (q *Queries) GetDiscoverSourceFaviconURL(ctx context.Context, sourceKey string) (*string, error) {
	row := q.db.QueryRowContext(ctx, getDiscoverSourceFaviconURL, sourceKey)
	var favicon_url *string
	err := row.Scan(&favicon_url)
	return favicon_url, err
}

const getDiscoverSourcePostsState = `-- name: GetDiscoverSourcePostsState :one
SELECT source_key, fetched_at, favicon_url, failure_count, next_retry_at, favicon_failure_count, favicon_next_retry_at FROM discover_source_posts_state WHERE source_key = ?
`

func (q *Queries) GetDiscoverSourcePostsState(ctx context.Context, sourceKey string) (DiscoverSourcePostsState, error) {
	row := q.db.QueryRowContext(ctx, getDiscoverSourcePostsState, sourceKey)
	var i DiscoverSourcePostsState
	err := row.Scan(
		&i.SourceKey,
		&i.FetchedAt,
		&i.FaviconUrl,
		&i.FailureCount,
		&i.NextRetryAt,
		&i.FaviconFailureCount,
		&i.FaviconNextRetryAt,
	)
	return i, err
}

const insertDiscoverSourcePost = `-- name: InsertDiscoverSourcePost :exec
INSERT INTO discover_source_posts (source_key, position, title, published_at, url, post_key)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertDiscoverSourcePostParams struct {
	SourceKey   string  `json:"source_key"`
	Position    int64   `json:"position"`
	Title       string  `json:"title"`
	PublishedAt *string `json:"published_at"`
	Url         *string `json:"url"`
	PostKey     string  `json:"post_key"`
}

func (q *Queries) InsertDiscoverSourcePost(ctx context.Context, arg InsertDiscoverSourcePostParams) error {
	_, err := q.db.ExecContext(ctx, insertDiscoverSourcePost,
		arg.SourceKey,
		arg.Position,
		arg.Title,
		arg.PublishedAt,
		arg.Url,
		arg.PostKey,
	)
	return err
}

const listDiscoverSourcePosts = `-- name: ListDiscoverSourcePosts :many
SELECT source_key, position, title, published_at, url, post_key
FROM discover_source_posts WHERE source_key = ? ORDER BY position ASC
`

func (q *Queries) ListDiscoverSourcePosts(ctx context.Context, sourceKey string) ([]DiscoverSourcePost, error) {
	rows, err := q.db.QueryContext(ctx, listDiscoverSourcePosts, sourceKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoverSourcePost
	for rows.Next() {
		var i DiscoverSourcePost
		if err := rows.Scan(
			&i.SourceKey,
			&i.Position,
			&i.Title,
			&i.PublishedAt,
			&i.Url,
			&i.PostKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDiscoverSourceFaviconDiscoveryFailure = `-- name: RecordDiscoverSourceFaviconDiscoveryFailure :exec
INSERT INTO discover_source_posts_state (source_key, favicon_failure_count, favicon_next_retry_at)
VALUES (?, ?, ?)
ON CONFLICT (source_key) DO UPDATE SET favicon_failure_count = excluded.favicon_failure_count, favicon_next_retry_at = excluded.favicon_next_retry_at
`

type RecordDiscoverSourceFaviconDiscoveryFailureParams struct {
	SourceKey           string  `json:"source_key"`
	FaviconFailureCount int64   `json:"favicon_failure_count"`
	FaviconNextRetryAt  *string `json:"favicon_next_retry_at"`
}

// Never touches favicon_url or the posts ladder: a discovery failure is orthogonal to both.
func (q *Queries) RecordDiscoverSourceFaviconDiscoveryFailure(ctx context.Context, arg RecordDiscoverSourceFaviconDiscoveryFailureParams) error {
	_, err := q.db.ExecContext(ctx, recordDiscoverSourceFaviconDiscoveryFailure, arg.SourceKey, arg.FaviconFailureCount, arg.FaviconNextRetryAt)
	return err
}

const recordDiscoverSourcePostsFailure = `-- name: RecordDiscoverSourcePostsFailure :exec
INSERT INTO discover_source_posts_state (source_key, fetched_at, favicon_url, failure_count, next_retry_at) VALUES (?, NULL, NULL, ?, ?)
ON CONFLICT (source_key) DO UPDATE SET failure_count = excluded.failure_count, next_retry_at = excluded.next_retry_at
`

type RecordDiscoverSourcePostsFailureParams struct {
	SourceKey    string  `json:"source_key"`
	FailureCount int64   `json:"failure_count"`
	NextRetryAt  *string `json:"next_retry_at"`
}

// Never touches fetched_at/favicon_url on conflict: a transient failure must not erase a prior success's payload (stale-while-error).
func (q *Queries) RecordDiscoverSourcePostsFailure(ctx context.Context, arg RecordDiscoverSourcePostsFailureParams) error {
	_, err := q.db.ExecContext(ctx, recordDiscoverSourcePostsFailure, arg.SourceKey, arg.FailureCount, arg.NextRetryAt)
	return err
}

const upsertDiscoverSourceFaviconURL = `-- name: UpsertDiscoverSourceFaviconURL :exec
INSERT INTO discover_source_posts_state (source_key, favicon_url, favicon_failure_count, favicon_next_retry_at)
VALUES (?, ?, 0, NULL)
ON CONFLICT (source_key) DO UPDATE SET favicon_url = excluded.favicon_url, favicon_failure_count = 0, favicon_next_retry_at = NULL
`

type UpsertDiscoverSourceFaviconURLParams struct {
	SourceKey  string  `json:"source_key"`
	FaviconUrl *string `json:"favicon_url"`
}

// On-demand discovery success; only touches the favicon columns, never the posts ladder (fetched_at/failure_count/next_retry_at).
func (q *Queries) UpsertDiscoverSourceFaviconURL(ctx context.Context, arg UpsertDiscoverSourceFaviconURLParams) error {
	_, err := q.db.ExecContext(ctx, upsertDiscoverSourceFaviconURL, arg.SourceKey, arg.FaviconUrl)
	return err
}

const upsertDiscoverSourcePostsState = `-- name: UpsertDiscoverSourcePostsState :exec
INSERT INTO discover_source_posts_state (source_key, fetched_at, favicon_url, failure_count, next_retry_at) VALUES (?, ?, ?, 0, NULL)
ON CONFLICT (source_key) DO UPDATE SET fetched_at = excluded.fetched_at, favicon_url = excluded.favicon_url, failure_count = 0, next_retry_at = NULL
`

type UpsertDiscoverSourcePostsStateParams struct {
	SourceKey  string  `json:"source_key"`
	FetchedAt  *string `json:"fetched_at"`
	FaviconUrl *string `json:"favicon_url"`
}

// Every success resets the failure ladder: a recovered source deserves a fresh backoff clock next time it fails.
func (q *Queries) UpsertDiscoverSourcePostsState(ctx context.Context, arg UpsertDiscoverSourcePostsStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertDiscoverSourcePostsState, arg.SourceKey, arg.FetchedAt, arg.FaviconUrl)
	return err
}
