// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discover_ingest.sql

package db

import (
	"context"
)

const getDiscoverIngestCursor = `-- name: GetDiscoverIngestCursor :one
SELECT seq, updated_at
FROM discover_ingest_cursor
WHERE id = 1
`

type GetDiscoverIngestCursorRow struct {
	Seq       int64  `json:"seq"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) GetDiscoverIngestCursor(ctx context.Context) (GetDiscoverIngestCursorRow, error) {
	row := q.db.QueryRowContext(ctx, getDiscoverIngestCursor)
	var i GetDiscoverIngestCursorRow
	err := row.Scan(&i.Seq, &i.UpdatedAt)
	return i, err
}

const upsertDiscoverIngestCursor = `-- name: UpsertDiscoverIngestCursor :exec
INSERT INTO discover_ingest_cursor (id, seq, updated_at)
VALUES (1, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    seq        = excluded.seq,
    updated_at = excluded.updated_at
`

type UpsertDiscoverIngestCursorParams struct {
	Seq       int64  `json:"seq"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) UpsertDiscoverIngestCursor(ctx context.Context, arg UpsertDiscoverIngestCursorParams) error {
	_, err := q.db.ExecContext(ctx, upsertDiscoverIngestCursor, arg.Seq, arg.UpdatedAt)
	return err
}
