// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discover_hides.sql

package db

import (
	"context"
)

const countDiscoverHidesForUser = `-- name: CountDiscoverHidesForUser :one
SELECT COUNT(*) FROM discover_hides WHERE did = ?
`

func (q *Queries) CountDiscoverHidesForUser(ctx context.Context, did string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDiscoverHidesForUser, did)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDiscoverHide = `-- name: GetDiscoverHide :one
SELECT did, target_kind, target_key, hidden_until, hide_count, created_at, updated_at
FROM discover_hides WHERE did = ? AND target_kind = ? AND target_key = ?
`

type GetDiscoverHideParams struct {
	Did        string `json:"did"`
	TargetKind string `json:"target_kind"`
	TargetKey  string `json:"target_key"`
}

func (q *Queries) GetDiscoverHide(ctx context.Context, arg GetDiscoverHideParams) (DiscoverHide, error) {
	row := q.db.QueryRowContext(ctx, getDiscoverHide, arg.Did, arg.TargetKind, arg.TargetKey)
	var i DiscoverHide
	err := row.Scan(
		&i.Did,
		&i.TargetKind,
		&i.TargetKey,
		&i.HiddenUntil,
		&i.HideCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveDiscoverHides = `-- name: ListActiveDiscoverHides :many
SELECT target_key
FROM discover_hides WHERE did = ? AND target_kind = ? AND hidden_until > ?
`

type ListActiveDiscoverHidesParams struct {
	Did         string `json:"did"`
	TargetKind  string `json:"target_kind"`
	HiddenUntil string `json:"hidden_until"`
}

// Scoped by did in the query itself (never fetch-then-compare in handlers).
func (q *Queries) ListActiveDiscoverHides(ctx context.Context, arg ListActiveDiscoverHidesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listActiveDiscoverHides, arg.Did, arg.TargetKind, arg.HiddenUntil)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var target_key string
		if err := rows.Scan(&target_key); err != nil {
			return nil, err
		}
		items = append(items, target_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDiscoverHide = `-- name: UpsertDiscoverHide :exec
INSERT INTO discover_hides (did, target_kind, target_key, hidden_until, hide_count, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (did, target_kind, target_key) DO UPDATE SET
    hidden_until = excluded.hidden_until,
    hide_count   = excluded.hide_count,
    updated_at   = excluded.updated_at
`

type UpsertDiscoverHideParams struct {
	Did         string `json:"did"`
	TargetKind  string `json:"target_kind"`
	TargetKey   string `json:"target_key"`
	HiddenUntil string `json:"hidden_until"`
	HideCount   int64  `json:"hide_count"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) UpsertDiscoverHide(ctx context.Context, arg UpsertDiscoverHideParams) error {
	_, err := q.db.ExecContext(ctx, upsertDiscoverHide,
		arg.Did,
		arg.TargetKind,
		arg.TargetKey,
		arg.HiddenUntil,
		arg.HideCount,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
