// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discover_resolutions.sql

package db

import (
	"context"
)

const getDiscoverPublicationResolution = `-- name: GetDiscoverPublicationResolution :one
SELECT publication_uri, canonical_key, kind, title, site_url, icon_url, failure_count, fetched_at, next_retry_at
FROM discover_publication_resolutions WHERE publication_uri = ?
`

func (q *Queries) GetDiscoverPublicationResolution(ctx context.Context, publicationUri string) (DiscoverPublicationResolution, error) {
	row := q.db.QueryRowContext(ctx, getDiscoverPublicationResolution, publicationUri)
	var i DiscoverPublicationResolution
	err := row.Scan(
		&i.PublicationUri,
		&i.CanonicalKey,
		&i.Kind,
		&i.Title,
		&i.SiteUrl,
		&i.IconUrl,
		&i.FailureCount,
		&i.FetchedAt,
		&i.NextRetryAt,
	)
	return i, err
}

const getDiscoverPublicationResolutionByCanonicalKey = `-- name: GetDiscoverPublicationResolutionByCanonicalKey :one
SELECT publication_uri, canonical_key, kind, title, site_url, icon_url, failure_count, fetched_at, next_retry_at
FROM discover_publication_resolutions WHERE canonical_key = ? LIMIT 1
`

func (q *Queries) GetDiscoverPublicationResolutionByCanonicalKey(ctx context.Context, canonicalKey *string) (DiscoverPublicationResolution, error) {
	row := q.db.QueryRowContext(ctx, getDiscoverPublicationResolutionByCanonicalKey, canonicalKey)
	var i DiscoverPublicationResolution
	err := row.Scan(
		&i.PublicationUri,
		&i.CanonicalKey,
		&i.Kind,
		&i.Title,
		&i.SiteUrl,
		&i.IconUrl,
		&i.FailureCount,
		&i.FetchedAt,
		&i.NextRetryAt,
	)
	return i, err
}

const upsertDiscoverPublicationResolution = `-- name: UpsertDiscoverPublicationResolution :exec
INSERT INTO discover_publication_resolutions (
    publication_uri, canonical_key, kind, title, site_url, icon_url, failure_count, fetched_at, next_retry_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (publication_uri) DO UPDATE SET
    canonical_key = excluded.canonical_key,
    kind          = excluded.kind,
    title         = excluded.title,
    site_url      = excluded.site_url,
    icon_url      = excluded.icon_url,
    failure_count = excluded.failure_count,
    fetched_at    = excluded.fetched_at,
    next_retry_at = excluded.next_retry_at
`

type UpsertDiscoverPublicationResolutionParams struct {
	PublicationUri string  `json:"publication_uri"`
	CanonicalKey   *string `json:"canonical_key"`
	Kind           *string `json:"kind"`
	Title          *string `json:"title"`
	SiteUrl        *string `json:"site_url"`
	IconUrl        *string `json:"icon_url"`
	FailureCount   int64   `json:"failure_count"`
	FetchedAt      string  `json:"fetched_at"`
	NextRetryAt    string  `json:"next_retry_at"`
}

func (q *Queries) UpsertDiscoverPublicationResolution(ctx context.Context, arg UpsertDiscoverPublicationResolutionParams) error {
	_, err := q.db.ExecContext(ctx, upsertDiscoverPublicationResolution,
		arg.PublicationUri,
		arg.CanonicalKey,
		arg.Kind,
		arg.Title,
		arg.SiteUrl,
		arg.IconUrl,
		arg.FailureCount,
		arg.FetchedAt,
		arg.NextRetryAt,
	)
	return err
}
