// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package db

import (
	"context"
)

const getFeedEntryBySlug = `-- name: GetFeedEntryBySlug :one
SELECT id, feed_url, guid, entry_slug, url, title, content_html, content_type, published_at, fetched_at, metadata, extracted_body
FROM feed_entries WHERE entry_slug = ?
`

func (q *Queries) GetFeedEntryBySlug(ctx context.Context, entrySlug string) (FeedEntry, error) {
	row := q.db.QueryRowContext(ctx, getFeedEntryBySlug, entrySlug)
	var i FeedEntry
	err := row.Scan(
		&i.ID,
		&i.FeedUrl,
		&i.Guid,
		&i.EntrySlug,
		&i.Url,
		&i.Title,
		&i.ContentHtml,
		&i.ContentType,
		&i.PublishedAt,
		&i.FetchedAt,
		&i.Metadata,
		&i.ExtractedBody,
	)
	return i, err
}

const listAllEntriesForUser = `-- name: ListAllEntriesForUser :many
SELECT
    e.id, e.feed_url, e.guid, e.entry_slug, e.url, e.title, e.content_html, e.content_type,
    e.published_at, e.fetched_at, e.metadata, e.extracted_body,
    COALESCE(us.custom_title, us.title) AS feed_title,
    f.site_url AS feed_site_url,
    f.icon_url AS feed_icon_url
FROM feed_entries e
JOIN feeds f ON f.feed_url = e.feed_url
JOIN user_subscriptions us ON us.feed_url = e.feed_url
WHERE us.did = ?
ORDER BY e.published_at DESC, e.id DESC
`

type ListAllEntriesForUserRow struct {
	ID            int64   `json:"id"`
	FeedUrl       string  `json:"feed_url"`
	Guid          string  `json:"guid"`
	EntrySlug     string  `json:"entry_slug"`
	Url           string  `json:"url"`
	Title         *string `json:"title"`
	ContentHtml   *string `json:"content_html"`
	ContentType   string  `json:"content_type"`
	PublishedAt   string  `json:"published_at"`
	FetchedAt     string  `json:"fetched_at"`
	Metadata      *string `json:"metadata"`
	ExtractedBody *string `json:"extracted_body"`
	FeedTitle     *string `json:"feed_title"`
	FeedSiteUrl   *string `json:"feed_site_url"`
	FeedIconUrl   *string `json:"feed_icon_url"`
}

func (q *Queries) ListAllEntriesForUser(ctx context.Context, did string) ([]ListAllEntriesForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllEntriesForUser, did)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllEntriesForUserRow
	for rows.Next() {
		var i ListAllEntriesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedUrl,
			&i.Guid,
			&i.EntrySlug,
			&i.Url,
			&i.Title,
			&i.ContentHtml,
			&i.ContentType,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.Metadata,
			&i.ExtractedBody,
			&i.FeedTitle,
			&i.FeedSiteUrl,
			&i.FeedIconUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDigestForUser = `-- name: ListDigestForUser :many
SELECT
    e.id, e.feed_url, e.guid, e.entry_slug, e.url, e.title, e.content_html, e.content_type,
    e.published_at, e.fetched_at, e.metadata, e.extracted_body,
    COALESCE(us.custom_title, us.title) AS feed_title,
    f.site_url AS feed_site_url,
    f.icon_url AS feed_icon_url
FROM feed_entries e
JOIN feeds f ON f.feed_url = e.feed_url
JOIN user_subscriptions us ON us.feed_url = e.feed_url
WHERE us.did = ?
  AND e.published_at >= ?
  AND e.published_at < ?
ORDER BY e.published_at DESC, e.id DESC
`

type ListDigestForUserParams struct {
	Did           string `json:"did"`
	PublishedAt   string `json:"published_at"`
	PublishedAt_2 string `json:"published_at_2"`
}

type ListDigestForUserRow struct {
	ID            int64   `json:"id"`
	FeedUrl       string  `json:"feed_url"`
	Guid          string  `json:"guid"`
	EntrySlug     string  `json:"entry_slug"`
	Url           string  `json:"url"`
	Title         *string `json:"title"`
	ContentHtml   *string `json:"content_html"`
	ContentType   string  `json:"content_type"`
	PublishedAt   string  `json:"published_at"`
	FetchedAt     string  `json:"fetched_at"`
	Metadata      *string `json:"metadata"`
	ExtractedBody *string `json:"extracted_body"`
	FeedTitle     *string `json:"feed_title"`
	FeedSiteUrl   *string `json:"feed_site_url"`
	FeedIconUrl   *string `json:"feed_icon_url"`
}

func (q *Queries) ListDigestForUser(ctx context.Context, arg ListDigestForUserParams) ([]ListDigestForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listDigestForUser, arg.Did, arg.PublishedAt, arg.PublishedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDigestForUserRow
	for rows.Next() {
		var i ListDigestForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedUrl,
			&i.Guid,
			&i.EntrySlug,
			&i.Url,
			&i.Title,
			&i.ContentHtml,
			&i.ContentType,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.Metadata,
			&i.ExtractedBody,
			&i.FeedTitle,
			&i.FeedSiteUrl,
			&i.FeedIconUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeedEntryExtractedBody = `-- name: UpdateFeedEntryExtractedBody :exec
UPDATE feed_entries SET extracted_body = ? WHERE id = ?
`

type UpdateFeedEntryExtractedBodyParams struct {
	ExtractedBody *string `json:"extracted_body"`
	ID            int64   `json:"id"`
}

func (q *Queries) UpdateFeedEntryExtractedBody(ctx context.Context, arg UpdateFeedEntryExtractedBodyParams) error {
	_, err := q.db.ExecContext(ctx, updateFeedEntryExtractedBody, arg.ExtractedBody, arg.ID)
	return err
}

const upsertFeedEntry = `-- name: UpsertFeedEntry :exec
INSERT INTO feed_entries (feed_url, guid, entry_slug, url, title, content_html, content_type, published_at, fetched_at, metadata)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (feed_url, guid) DO UPDATE SET
    url          = excluded.url,
    title        = excluded.title,
    content_html = excluded.content_html,
    content_type = excluded.content_type,
    published_at = excluded.published_at,
    fetched_at   = excluded.fetched_at,
    metadata     = excluded.metadata
`

type UpsertFeedEntryParams struct {
	FeedUrl     string  `json:"feed_url"`
	Guid        string  `json:"guid"`
	EntrySlug   string  `json:"entry_slug"`
	Url         string  `json:"url"`
	Title       *string `json:"title"`
	ContentHtml *string `json:"content_html"`
	ContentType string  `json:"content_type"`
	PublishedAt string  `json:"published_at"`
	FetchedAt   string  `json:"fetched_at"`
	Metadata    *string `json:"metadata"`
}

func (q *Queries) UpsertFeedEntry(ctx context.Context, arg UpsertFeedEntryParams) error {
	_, err := q.db.ExecContext(ctx, upsertFeedEntry,
		arg.FeedUrl,
		arg.Guid,
		arg.EntrySlug,
		arg.Url,
		arg.Title,
		arg.ContentHtml,
		arg.ContentType,
		arg.PublishedAt,
		arg.FetchedAt,
		arg.Metadata,
	)
	return err
}
