// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: follows.sql

package db

import (
	"context"
)

const deleteUserFollow = `-- name: DeleteUserFollow :exec
DELETE FROM user_follows WHERE did = ? AND rkey = ?
`

type DeleteUserFollowParams struct {
	Did  string `json:"did"`
	Rkey string `json:"rkey"`
}

func (q *Queries) DeleteUserFollow(ctx context.Context, arg DeleteUserFollowParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserFollow, arg.Did, arg.Rkey)
	return err
}

const getUserFollow = `-- name: GetUserFollow :one
SELECT did, rkey, at_uri, subject_did, created_at, updated_at
FROM user_follows WHERE did = ? AND rkey = ?
`

type GetUserFollowParams struct {
	Did  string `json:"did"`
	Rkey string `json:"rkey"`
}

func (q *Queries) GetUserFollow(ctx context.Context, arg GetUserFollowParams) (UserFollow, error) {
	row := q.db.QueryRowContext(ctx, getUserFollow, arg.Did, arg.Rkey)
	var i UserFollow
	err := row.Scan(
		&i.Did,
		&i.Rkey,
		&i.AtUri,
		&i.SubjectDid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserFollowBySubjectDID = `-- name: GetUserFollowBySubjectDID :one
SELECT did, rkey, at_uri, subject_did, created_at, updated_at
FROM user_follows
WHERE did = ? AND subject_did = ? AND subject_did <> did
`

type GetUserFollowBySubjectDIDParams struct {
	Did        string `json:"did"`
	SubjectDid string `json:"subject_did"`
}

func (q *Queries) GetUserFollowBySubjectDID(ctx context.Context, arg GetUserFollowBySubjectDIDParams) (UserFollow, error) {
	row := q.db.QueryRowContext(ctx, getUserFollowBySubjectDID, arg.Did, arg.SubjectDid)
	var i UserFollow
	err := row.Scan(
		&i.Did,
		&i.Rkey,
		&i.AtUri,
		&i.SubjectDid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserFollows = `-- name: ListUserFollows :many
SELECT did, rkey, at_uri, subject_did, created_at, updated_at
FROM user_follows
WHERE did = ? AND subject_did <> did
ORDER BY created_at DESC
`

func (q *Queries) ListUserFollows(ctx context.Context, did string) ([]UserFollow, error) {
	rows, err := q.db.QueryContext(ctx, listUserFollows, did)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserFollow
	for rows.Next() {
		var i UserFollow
		if err := rows.Scan(
			&i.Did,
			&i.Rkey,
			&i.AtUri,
			&i.SubjectDid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserFollowsForSync = `-- name: ListUserFollowsForSync :many
SELECT did, rkey, at_uri, subject_did FROM user_follows WHERE did = ?
`

type ListUserFollowsForSyncRow struct {
	Did        string `json:"did"`
	Rkey       string `json:"rkey"`
	AtUri      string `json:"at_uri"`
	SubjectDid string `json:"subject_did"`
}

// Snapshot of a user's local follow index, used by sync_user to diff against
// the PDS and reconcile inserts/deletes.
func (q *Queries) ListUserFollowsForSync(ctx context.Context, did string) ([]ListUserFollowsForSyncRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserFollowsForSync, did)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserFollowsForSyncRow
	for rows.Next() {
		var i ListUserFollowsForSyncRow
		if err := rows.Scan(
			&i.Did,
			&i.Rkey,
			&i.AtUri,
			&i.SubjectDid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserFollow = `-- name: UpsertUserFollow :exec
INSERT INTO user_follows (
    did, rkey, at_uri, subject_did, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (did, rkey) DO UPDATE SET
    at_uri      = excluded.at_uri,
    subject_did = excluded.subject_did,
    updated_at  = excluded.updated_at
`

type UpsertUserFollowParams struct {
	Did        string `json:"did"`
	Rkey       string `json:"rkey"`
	AtUri      string `json:"at_uri"`
	SubjectDid string `json:"subject_did"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

func (q *Queries) UpsertUserFollow(ctx context.Context, arg UpsertUserFollowParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserFollow,
		arg.Did,
		arg.Rkey,
		arg.AtUri,
		arg.SubjectDid,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
