// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Feed struct {
	FeedUrl             string  `json:"feed_url"`
	Kind                string  `json:"kind"`
	SiteUrl             *string `json:"site_url"`
	Title               *string `json:"title"`
	Etag                *string `json:"etag"`
	LastModified        *string `json:"last_modified"`
	LastFetchedAt       *string `json:"last_fetched_at"`
	IconUrl             *string `json:"icon_url"`
	IconFetchedAt       *string `json:"icon_fetched_at"`
	CreatedAt           string  `json:"created_at"`
	UpdatedAt           string  `json:"updated_at"`
	ConsecutiveFailures int64   `json:"consecutive_failures"`
	NextFetchAt         *string `json:"next_fetch_at"`
}

type FeedEntry struct {
	ID            int64   `json:"id"`
	FeedUrl       string  `json:"feed_url"`
	Guid          string  `json:"guid"`
	EntrySlug     string  `json:"entry_slug"`
	Url           string  `json:"url"`
	Title         *string `json:"title"`
	ContentHtml   *string `json:"content_html"`
	ContentType   string  `json:"content_type"`
	PublishedAt   string  `json:"published_at"`
	FetchedAt     string  `json:"fetched_at"`
	Metadata      *string `json:"metadata"`
	ExtractedBody *string `json:"extracted_body"`
	RecordCid     *string `json:"record_cid"`
}

type NewsletterAddress struct {
	Did       string `json:"did"`
	LocalPart string `json:"local_part"`
	CreatedAt string `json:"created_at"`
}

type NewsletterInlineAsset struct {
	Token       string `json:"token"`
	MessageID   string `json:"message_id"`
	ContentID   string `json:"content_id"`
	MediaType   string `json:"media_type"`
	Data        []byte `json:"data"`
	ContentHash string `json:"content_hash"`
	CreatedAt   string `json:"created_at"`
}

type NewsletterMessage struct {
	ID                     string  `json:"id"`
	Did                    string  `json:"did"`
	SourceID               string  `json:"source_id"`
	EntrySlug              string  `json:"entry_slug"`
	DedupeKey              string  `json:"dedupe_key"`
	MessageID              *string `json:"message_id"`
	Title                  *string `json:"title"`
	SenderName             *string `json:"sender_name"`
	SenderAddress          string  `json:"sender_address"`
	SentAt                 *string `json:"sent_at"`
	ReceivedAt             string  `json:"received_at"`
	BodyHtmlBlocked        *string `json:"body_html_blocked"`
	BodyHtmlRemote         *string `json:"body_html_remote"`
	BodyText               *string `json:"body_text"`
	HasBlockedRemoteImages int64   `json:"has_blocked_remote_images"`
	RemoteImagesAllowed    int64   `json:"remote_images_allowed"`
	AttachmentSummary      *string `json:"attachment_summary"`
	StorageBytes           int64   `json:"storage_bytes"`
	CreatedAt              string  `json:"created_at"`
	UpdatedAt              string  `json:"updated_at"`
}

type NewsletterReceipt struct {
	ID                 string  `json:"id"`
	Did                string  `json:"did"`
	EnvelopeFrom       string  `json:"envelope_from"`
	Recipient          string  `json:"recipient"`
	RecipientLocalPart string  `json:"recipient_local_part"`
	ReceivedAt         string  `json:"received_at"`
	RawMime            []byte  `json:"raw_mime"`
	ReservedBytes      int64   `json:"reserved_bytes"`
	Attempts           int64   `json:"attempts"`
	LastError          *string `json:"last_error"`
	NextAttemptAt      *string `json:"next_attempt_at"`
	CreatedAt          string  `json:"created_at"`
}

type NewsletterSafe struct {
	ID        string `json:"id"`
	Did       string `json:"did"`
	MessageID string `json:"message_id"`
	CreatedAt string `json:"created_at"`
}

type NewsletterSource struct {
	ID              string  `json:"id"`
	Did             string  `json:"did"`
	SourceKey       string  `json:"source_key"`
	IdentityKind    string  `json:"identity_kind"`
	IdentityValue   *string `json:"identity_value"`
	Title           string  `json:"title"`
	SenderName      *string `json:"sender_name"`
	SenderAddress   string  `json:"sender_address"`
	Status          string  `json:"status"`
	AcceptAfter     *string `json:"accept_after"`
	IsPrimary       int64   `json:"is_primary"`
	Tags            string  `json:"tags"`
	FirstReceivedAt *string `json:"first_received_at"`
	LastReceivedAt  *string `json:"last_received_at"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
}

type OauthAuthRequest struct {
	State     string `json:"state"`
	Data      []byte `json:"data"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
}

type OauthSession struct {
	Did       string `json:"did"`
	SessionID string `json:"session_id"`
	Data      []byte `json:"data"`
	UpdatedAt string `json:"updated_at"`
}

type UserSave struct {
	Did       string  `json:"did"`
	Rkey      string  `json:"rkey"`
	AtUri     string  `json:"at_uri"`
	ItemUrl   string  `json:"item_url"`
	FeedUrl   *string `json:"feed_url"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
}

type UserSubscription struct {
	Did         string  `json:"did"`
	Rkey        string  `json:"rkey"`
	AtUri       string  `json:"at_uri"`
	FeedUrl     string  `json:"feed_url"`
	Kind        string  `json:"kind"`
	SidecarRkey *string `json:"sidecar_rkey"`
	Title       *string `json:"title"`
	IsPrimary   int64   `json:"is_primary"`
	Tags        *string `json:"tags"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
}
