// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type OauthAuthRequest struct {
	State     string `json:"state"`
	Data      []byte `json:"data"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
}

type OauthSession struct {
	Did       string `json:"did"`
	SessionID string `json:"session_id"`
	Data      []byte `json:"data"`
	UpdatedAt string `json:"updated_at"`
}
