// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: newsletters.sql

package db

import (
	"context"
)

const allowNewsletterRemoteImages = `-- name: AllowNewsletterRemoteImages :exec
UPDATE newsletter_messages SET remote_images_allowed = 1, updated_at = ?3
WHERE did = ?1 AND id = ?2
`

type AllowNewsletterRemoteImagesParams struct {
	Did       string `json:"did"`
	ID        string `json:"id"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) AllowNewsletterRemoteImages(ctx context.Context, arg AllowNewsletterRemoteImagesParams) error {
	_, err := q.db.ExecContext(ctx, allowNewsletterRemoteImages, arg.Did, arg.ID, arg.UpdatedAt)
	return err
}

const createManualNewsletterSource = `-- name: CreateManualNewsletterSource :exec
INSERT INTO newsletter_sources (
    id, did, source_key, identity_kind, title, status, created_at, updated_at
) VALUES (?1, ?2, ?3, 'manual', ?4, 'active', ?5, ?5)
`

type CreateManualNewsletterSourceParams struct {
	ID        string `json:"id"`
	Did       string `json:"did"`
	SourceKey string `json:"source_key"`
	Title     string `json:"title"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) CreateManualNewsletterSource(ctx context.Context, arg CreateManualNewsletterSourceParams) error {
	_, err := q.db.ExecContext(ctx, createManualNewsletterSource,
		arg.ID,
		arg.Did,
		arg.SourceKey,
		arg.Title,
		arg.CreatedAt,
	)
	return err
}

const createNewsletterAddress = `-- name: CreateNewsletterAddress :exec
INSERT INTO newsletter_addresses (did, local_part, created_at)
VALUES (?1, ?2, ?3)
ON CONFLICT (did) DO NOTHING
`

type CreateNewsletterAddressParams struct {
	Did       string `json:"did"`
	LocalPart string `json:"local_part"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) CreateNewsletterAddress(ctx context.Context, arg CreateNewsletterAddressParams) error {
	_, err := q.db.ExecContext(ctx, createNewsletterAddress, arg.Did, arg.LocalPart, arg.CreatedAt)
	return err
}

const createNewsletterInlineAsset = `-- name: CreateNewsletterInlineAsset :exec
INSERT INTO newsletter_inline_assets (
    token, message_id, content_id, media_type, data, content_hash, created_at
) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
ON CONFLICT (message_id, content_id) DO NOTHING
`

type CreateNewsletterInlineAssetParams struct {
	Token       string `json:"token"`
	MessageID   string `json:"message_id"`
	ContentID   string `json:"content_id"`
	MediaType   string `json:"media_type"`
	Data        []byte `json:"data"`
	ContentHash string `json:"content_hash"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) CreateNewsletterInlineAsset(ctx context.Context, arg CreateNewsletterInlineAssetParams) error {
	_, err := q.db.ExecContext(ctx, createNewsletterInlineAsset,
		arg.Token,
		arg.MessageID,
		arg.ContentID,
		arg.MediaType,
		arg.Data,
		arg.ContentHash,
		arg.CreatedAt,
	)
	return err
}

const createNewsletterMessage = `-- name: CreateNewsletterMessage :one
INSERT INTO newsletter_messages (
    id, did, source_id, entry_slug, dedupe_key, message_id, title,
    sender_name, sender_address, sent_at, received_at,
    body_html_blocked, body_html_remote, body_text,
    has_blocked_remote_images, attachment_summary, storage_bytes, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7,
    ?8, ?9, ?10, ?11,
    ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?18
)
ON CONFLICT (did, dedupe_key) DO NOTHING
RETURNING id
`

type CreateNewsletterMessageParams struct {
	ID                     string  `json:"id"`
	Did                    string  `json:"did"`
	SourceID               string  `json:"source_id"`
	EntrySlug              string  `json:"entry_slug"`
	DedupeKey              string  `json:"dedupe_key"`
	MessageID              *string `json:"message_id"`
	Title                  *string `json:"title"`
	SenderName             *string `json:"sender_name"`
	SenderAddress          string  `json:"sender_address"`
	SentAt                 *string `json:"sent_at"`
	ReceivedAt             string  `json:"received_at"`
	BodyHtmlBlocked        *string `json:"body_html_blocked"`
	BodyHtmlRemote         *string `json:"body_html_remote"`
	BodyText               *string `json:"body_text"`
	HasBlockedRemoteImages int64   `json:"has_blocked_remote_images"`
	AttachmentSummary      *string `json:"attachment_summary"`
	StorageBytes           int64   `json:"storage_bytes"`
	CreatedAt              string  `json:"created_at"`
}

func (q *Queries) CreateNewsletterMessage(ctx context.Context, arg CreateNewsletterMessageParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createNewsletterMessage,
		arg.ID,
		arg.Did,
		arg.SourceID,
		arg.EntrySlug,
		arg.DedupeKey,
		arg.MessageID,
		arg.Title,
		arg.SenderName,
		arg.SenderAddress,
		arg.SentAt,
		arg.ReceivedAt,
		arg.BodyHtmlBlocked,
		arg.BodyHtmlRemote,
		arg.BodyText,
		arg.HasBlockedRemoteImages,
		arg.AttachmentSummary,
		arg.StorageBytes,
		arg.CreatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createNewsletterReceipt = `-- name: CreateNewsletterReceipt :exec
INSERT INTO newsletter_receipts (
    id, did, envelope_from, recipient, received_at, raw_mime, reserved_bytes, created_at
) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
`

type CreateNewsletterReceiptParams struct {
	ID            string `json:"id"`
	Did           string `json:"did"`
	EnvelopeFrom  string `json:"envelope_from"`
	Recipient     string `json:"recipient"`
	ReceivedAt    string `json:"received_at"`
	RawMime       []byte `json:"raw_mime"`
	ReservedBytes int64  `json:"reserved_bytes"`
	CreatedAt     string `json:"created_at"`
}

func (q *Queries) CreateNewsletterReceipt(ctx context.Context, arg CreateNewsletterReceiptParams) error {
	_, err := q.db.ExecContext(ctx, createNewsletterReceipt,
		arg.ID,
		arg.Did,
		arg.EnvelopeFrom,
		arg.Recipient,
		arg.ReceivedAt,
		arg.RawMime,
		arg.ReservedBytes,
		arg.CreatedAt,
	)
	return err
}

const createNewsletterSave = `-- name: CreateNewsletterSave :exec
INSERT INTO newsletter_saves (id, did, message_id, created_at)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (did, message_id) DO NOTHING
`

type CreateNewsletterSaveParams struct {
	ID        string `json:"id"`
	Did       string `json:"did"`
	MessageID string `json:"message_id"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) CreateNewsletterSave(ctx context.Context, arg CreateNewsletterSaveParams) error {
	_, err := q.db.ExecContext(ctx, createNewsletterSave,
		arg.ID,
		arg.Did,
		arg.MessageID,
		arg.CreatedAt,
	)
	return err
}

const createNewsletterSource = `-- name: CreateNewsletterSource :exec
INSERT INTO newsletter_sources (
    id, did, source_key, identity_kind, identity_value, title,
    sender_name, sender_address, status, first_received_at,
    last_received_at, created_at, updated_at
) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, 'active', ?9, ?9, ?9, ?9)
ON CONFLICT (did, source_key) DO NOTHING
`

type CreateNewsletterSourceParams struct {
	ID              string  `json:"id"`
	Did             string  `json:"did"`
	SourceKey       string  `json:"source_key"`
	IdentityKind    string  `json:"identity_kind"`
	IdentityValue   *string `json:"identity_value"`
	Title           string  `json:"title"`
	SenderName      *string `json:"sender_name"`
	SenderAddress   string  `json:"sender_address"`
	FirstReceivedAt *string `json:"first_received_at"`
}

func (q *Queries) CreateNewsletterSource(ctx context.Context, arg CreateNewsletterSourceParams) error {
	_, err := q.db.ExecContext(ctx, createNewsletterSource,
		arg.ID,
		arg.Did,
		arg.SourceKey,
		arg.IdentityKind,
		arg.IdentityValue,
		arg.Title,
		arg.SenderName,
		arg.SenderAddress,
		arg.FirstReceivedAt,
	)
	return err
}

const deleteNewsletterReceipt = `-- name: DeleteNewsletterReceipt :exec
DELETE FROM newsletter_receipts WHERE id = ?1
`

func (q *Queries) DeleteNewsletterReceipt(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNewsletterReceipt, id)
	return err
}

const deleteNewsletterSave = `-- name: DeleteNewsletterSave :exec
DELETE FROM newsletter_saves WHERE did = ?1 AND id = ?2
`

type DeleteNewsletterSaveParams struct {
	Did string `json:"did"`
	ID  string `json:"id"`
}

func (q *Queries) DeleteNewsletterSave(ctx context.Context, arg DeleteNewsletterSaveParams) error {
	_, err := q.db.ExecContext(ctx, deleteNewsletterSave, arg.Did, arg.ID)
	return err
}

const deleteStoppedUnsavedNewsletterMessage = `-- name: DeleteStoppedUnsavedNewsletterMessage :exec
DELETE FROM newsletter_messages AS m
WHERE m.did = ?1 AND m.id = ?2
  AND NOT EXISTS (SELECT 1 FROM newsletter_saves s WHERE s.did = ?1 AND s.message_id = ?2)
  AND EXISTS (SELECT 1 FROM newsletter_sources src WHERE src.did = ?1 AND src.id = m.source_id AND src.status = 'stopped')
`

type DeleteStoppedUnsavedNewsletterMessageParams struct {
	Did string `json:"did"`
	ID  string `json:"id"`
}

func (q *Queries) DeleteStoppedUnsavedNewsletterMessage(ctx context.Context, arg DeleteStoppedUnsavedNewsletterMessageParams) error {
	_, err := q.db.ExecContext(ctx, deleteStoppedUnsavedNewsletterMessage, arg.Did, arg.ID)
	return err
}

const deleteUnsavedNewsletterMessages = `-- name: DeleteUnsavedNewsletterMessages :exec
DELETE FROM newsletter_messages AS m
WHERE m.did = ?1 AND m.source_id = ?2
  AND NOT EXISTS (
      SELECT 1 FROM newsletter_saves s
      WHERE s.did = m.did
        AND s.message_id = m.id
  )
`

type DeleteUnsavedNewsletterMessagesParams struct {
	Did      string `json:"did"`
	SourceID string `json:"source_id"`
}

func (q *Queries) DeleteUnsavedNewsletterMessages(ctx context.Context, arg DeleteUnsavedNewsletterMessagesParams) error {
	_, err := q.db.ExecContext(ctx, deleteUnsavedNewsletterMessages, arg.Did, arg.SourceID)
	return err
}

const enableNewsletterSource = `-- name: EnableNewsletterSource :exec
UPDATE newsletter_sources
SET status = 'active', accept_after = ?3, updated_at = ?3
WHERE did = ?1 AND id = ?2
`

type EnableNewsletterSourceParams struct {
	Did         string  `json:"did"`
	ID          string  `json:"id"`
	AcceptAfter *string `json:"accept_after"`
}

func (q *Queries) EnableNewsletterSource(ctx context.Context, arg EnableNewsletterSourceParams) error {
	_, err := q.db.ExecContext(ctx, enableNewsletterSource, arg.Did, arg.ID, arg.AcceptAfter)
	return err
}

const getNewsletterAddress = `-- name: GetNewsletterAddress :one
SELECT did, local_part, created_at
FROM newsletter_addresses
WHERE did = ?1
`

func (q *Queries) GetNewsletterAddress(ctx context.Context, did string) (NewsletterAddress, error) {
	row := q.db.QueryRowContext(ctx, getNewsletterAddress, did)
	var i NewsletterAddress
	err := row.Scan(&i.Did, &i.LocalPart, &i.CreatedAt)
	return i, err
}

const getNewsletterAddressByLocalPart = `-- name: GetNewsletterAddressByLocalPart :one
SELECT did, local_part, created_at
FROM newsletter_addresses
WHERE local_part = ?1
`

func (q *Queries) GetNewsletterAddressByLocalPart(ctx context.Context, localPart string) (NewsletterAddress, error) {
	row := q.db.QueryRowContext(ctx, getNewsletterAddressByLocalPart, localPart)
	var i NewsletterAddress
	err := row.Scan(&i.Did, &i.LocalPart, &i.CreatedAt)
	return i, err
}

const getNewsletterGlobalStorageBytes = `-- name: GetNewsletterGlobalStorageBytes :one
SELECT CAST(
    COALESCE((SELECT SUM(reserved_bytes) FROM newsletter_receipts), 0) +
    COALESCE((SELECT SUM(storage_bytes) FROM newsletter_messages), 0)
AS INTEGER) AS storage_bytes
`

func (q *Queries) GetNewsletterGlobalStorageBytes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNewsletterGlobalStorageBytes)
	var storage_bytes int64
	err := row.Scan(&storage_bytes)
	return storage_bytes, err
}

const getNewsletterInlineAsset = `-- name: GetNewsletterInlineAsset :one
SELECT a.token, a.message_id, a.content_id, a.media_type, a.data, a.content_hash, a.created_at
FROM newsletter_inline_assets a
JOIN newsletter_messages m ON m.id = a.message_id
WHERE m.did = ?1 AND a.token = ?2
`

type GetNewsletterInlineAssetParams struct {
	Did   string `json:"did"`
	Token string `json:"token"`
}

func (q *Queries) GetNewsletterInlineAsset(ctx context.Context, arg GetNewsletterInlineAssetParams) (NewsletterInlineAsset, error) {
	row := q.db.QueryRowContext(ctx, getNewsletterInlineAsset, arg.Did, arg.Token)
	var i NewsletterInlineAsset
	err := row.Scan(
		&i.Token,
		&i.MessageID,
		&i.ContentID,
		&i.MediaType,
		&i.Data,
		&i.ContentHash,
		&i.CreatedAt,
	)
	return i, err
}

const getNewsletterMessage = `-- name: GetNewsletterMessage :one
SELECT m.id, m.did, m.source_id, m.entry_slug, m.dedupe_key, m.message_id, m.title, m.sender_name, m.sender_address, m.sent_at, m.received_at, m.body_html_blocked, m.body_html_remote, m.body_text, m.has_blocked_remote_images, m.remote_images_allowed, m.attachment_summary, m.storage_bytes, m.created_at, m.updated_at, s.title AS source_title, s.status AS source_status, s.is_primary AS source_primary,
       sv.id AS save_id, sv.created_at AS saved_at
FROM newsletter_messages m
JOIN newsletter_sources s ON s.id = m.source_id AND s.did = m.did
LEFT JOIN newsletter_saves sv ON sv.message_id = m.id AND sv.did = m.did
WHERE m.did = ?1 AND m.id = ?2
`

type GetNewsletterMessageParams struct {
	Did string `json:"did"`
	ID  string `json:"id"`
}

type GetNewsletterMessageRow struct {
	ID                     string  `json:"id"`
	Did                    string  `json:"did"`
	SourceID               string  `json:"source_id"`
	EntrySlug              string  `json:"entry_slug"`
	DedupeKey              string  `json:"dedupe_key"`
	MessageID              *string `json:"message_id"`
	Title                  *string `json:"title"`
	SenderName             *string `json:"sender_name"`
	SenderAddress          string  `json:"sender_address"`
	SentAt                 *string `json:"sent_at"`
	ReceivedAt             string  `json:"received_at"`
	BodyHtmlBlocked        *string `json:"body_html_blocked"`
	BodyHtmlRemote         *string `json:"body_html_remote"`
	BodyText               *string `json:"body_text"`
	HasBlockedRemoteImages int64   `json:"has_blocked_remote_images"`
	RemoteImagesAllowed    int64   `json:"remote_images_allowed"`
	AttachmentSummary      *string `json:"attachment_summary"`
	StorageBytes           int64   `json:"storage_bytes"`
	CreatedAt              string  `json:"created_at"`
	UpdatedAt              string  `json:"updated_at"`
	SourceTitle            string  `json:"source_title"`
	SourceStatus           string  `json:"source_status"`
	SourcePrimary          int64   `json:"source_primary"`
	SaveID                 *string `json:"save_id"`
	SavedAt                *string `json:"saved_at"`
}

func (q *Queries) GetNewsletterMessage(ctx context.Context, arg GetNewsletterMessageParams) (GetNewsletterMessageRow, error) {
	row := q.db.QueryRowContext(ctx, getNewsletterMessage, arg.Did, arg.ID)
	var i GetNewsletterMessageRow
	err := row.Scan(
		&i.ID,
		&i.Did,
		&i.SourceID,
		&i.EntrySlug,
		&i.DedupeKey,
		&i.MessageID,
		&i.Title,
		&i.SenderName,
		&i.SenderAddress,
		&i.SentAt,
		&i.ReceivedAt,
		&i.BodyHtmlBlocked,
		&i.BodyHtmlRemote,
		&i.BodyText,
		&i.HasBlockedRemoteImages,
		&i.RemoteImagesAllowed,
		&i.AttachmentSummary,
		&i.StorageBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceTitle,
		&i.SourceStatus,
		&i.SourcePrimary,
		&i.SaveID,
		&i.SavedAt,
	)
	return i, err
}

const getNewsletterMessageBySlug = `-- name: GetNewsletterMessageBySlug :one
SELECT m.id, m.did, m.source_id, m.entry_slug, m.dedupe_key, m.message_id, m.title, m.sender_name, m.sender_address, m.sent_at, m.received_at, m.body_html_blocked, m.body_html_remote, m.body_text, m.has_blocked_remote_images, m.remote_images_allowed, m.attachment_summary, m.storage_bytes, m.created_at, m.updated_at, s.title AS source_title, s.status AS source_status, s.is_primary AS source_primary,
       sv.id AS save_id, sv.created_at AS saved_at
FROM newsletter_messages m
JOIN newsletter_sources s ON s.id = m.source_id AND s.did = m.did
LEFT JOIN newsletter_saves sv ON sv.message_id = m.id AND sv.did = m.did
WHERE m.did = ?1 AND m.entry_slug = ?2
`

type GetNewsletterMessageBySlugParams struct {
	Did       string `json:"did"`
	EntrySlug string `json:"entry_slug"`
}

type GetNewsletterMessageBySlugRow struct {
	ID                     string  `json:"id"`
	Did                    string  `json:"did"`
	SourceID               string  `json:"source_id"`
	EntrySlug              string  `json:"entry_slug"`
	DedupeKey              string  `json:"dedupe_key"`
	MessageID              *string `json:"message_id"`
	Title                  *string `json:"title"`
	SenderName             *string `json:"sender_name"`
	SenderAddress          string  `json:"sender_address"`
	SentAt                 *string `json:"sent_at"`
	ReceivedAt             string  `json:"received_at"`
	BodyHtmlBlocked        *string `json:"body_html_blocked"`
	BodyHtmlRemote         *string `json:"body_html_remote"`
	BodyText               *string `json:"body_text"`
	HasBlockedRemoteImages int64   `json:"has_blocked_remote_images"`
	RemoteImagesAllowed    int64   `json:"remote_images_allowed"`
	AttachmentSummary      *string `json:"attachment_summary"`
	StorageBytes           int64   `json:"storage_bytes"`
	CreatedAt              string  `json:"created_at"`
	UpdatedAt              string  `json:"updated_at"`
	SourceTitle            string  `json:"source_title"`
	SourceStatus           string  `json:"source_status"`
	SourcePrimary          int64   `json:"source_primary"`
	SaveID                 *string `json:"save_id"`
	SavedAt                *string `json:"saved_at"`
}

func (q *Queries) GetNewsletterMessageBySlug(ctx context.Context, arg GetNewsletterMessageBySlugParams) (GetNewsletterMessageBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getNewsletterMessageBySlug, arg.Did, arg.EntrySlug)
	var i GetNewsletterMessageBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Did,
		&i.SourceID,
		&i.EntrySlug,
		&i.DedupeKey,
		&i.MessageID,
		&i.Title,
		&i.SenderName,
		&i.SenderAddress,
		&i.SentAt,
		&i.ReceivedAt,
		&i.BodyHtmlBlocked,
		&i.BodyHtmlRemote,
		&i.BodyText,
		&i.HasBlockedRemoteImages,
		&i.RemoteImagesAllowed,
		&i.AttachmentSummary,
		&i.StorageBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceTitle,
		&i.SourceStatus,
		&i.SourcePrimary,
		&i.SaveID,
		&i.SavedAt,
	)
	return i, err
}

const getNewsletterOwnerStorageBytes = `-- name: GetNewsletterOwnerStorageBytes :one
SELECT CAST(
    COALESCE((SELECT SUM(r.reserved_bytes) FROM newsletter_receipts r WHERE r.did = ?1), 0) +
    COALESCE((SELECT SUM(m.storage_bytes) FROM newsletter_messages m WHERE m.did = ?1), 0)
AS INTEGER) AS storage_bytes
`

func (q *Queries) GetNewsletterOwnerStorageBytes(ctx context.Context, did string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNewsletterOwnerStorageBytes, did)
	var storage_bytes int64
	err := row.Scan(&storage_bytes)
	return storage_bytes, err
}

const getNewsletterSave = `-- name: GetNewsletterSave :one
SELECT id, did, message_id, created_at FROM newsletter_saves WHERE did = ?1 AND id = ?2
`

type GetNewsletterSaveParams struct {
	Did string `json:"did"`
	ID  string `json:"id"`
}

func (q *Queries) GetNewsletterSave(ctx context.Context, arg GetNewsletterSaveParams) (NewsletterSafe, error) {
	row := q.db.QueryRowContext(ctx, getNewsletterSave, arg.Did, arg.ID)
	var i NewsletterSafe
	err := row.Scan(
		&i.ID,
		&i.Did,
		&i.MessageID,
		&i.CreatedAt,
	)
	return i, err
}

const getNewsletterSaveForMessage = `-- name: GetNewsletterSaveForMessage :one
SELECT id, did, message_id, created_at FROM newsletter_saves WHERE did = ?1 AND message_id = ?2
`

type GetNewsletterSaveForMessageParams struct {
	Did       string `json:"did"`
	MessageID string `json:"message_id"`
}

func (q *Queries) GetNewsletterSaveForMessage(ctx context.Context, arg GetNewsletterSaveForMessageParams) (NewsletterSafe, error) {
	row := q.db.QueryRowContext(ctx, getNewsletterSaveForMessage, arg.Did, arg.MessageID)
	var i NewsletterSafe
	err := row.Scan(
		&i.ID,
		&i.Did,
		&i.MessageID,
		&i.CreatedAt,
	)
	return i, err
}

const getNewsletterSource = `-- name: GetNewsletterSource :one
SELECT id, did, source_key, identity_kind, identity_value, title, sender_name, sender_address, status, accept_after, is_primary, tags, first_received_at, last_received_at, created_at, updated_at FROM newsletter_sources WHERE did = ?1 AND id = ?2
`

type GetNewsletterSourceParams struct {
	Did string `json:"did"`
	ID  string `json:"id"`
}

func (q *Queries) GetNewsletterSource(ctx context.Context, arg GetNewsletterSourceParams) (NewsletterSource, error) {
	row := q.db.QueryRowContext(ctx, getNewsletterSource, arg.Did, arg.ID)
	var i NewsletterSource
	err := row.Scan(
		&i.ID,
		&i.Did,
		&i.SourceKey,
		&i.IdentityKind,
		&i.IdentityValue,
		&i.Title,
		&i.SenderName,
		&i.SenderAddress,
		&i.Status,
		&i.AcceptAfter,
		&i.IsPrimary,
		&i.Tags,
		&i.FirstReceivedAt,
		&i.LastReceivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNewsletterSourceByKey = `-- name: GetNewsletterSourceByKey :one
SELECT id, did, source_key, identity_kind, identity_value, title, sender_name, sender_address, status, accept_after, is_primary, tags, first_received_at, last_received_at, created_at, updated_at FROM newsletter_sources WHERE did = ?1 AND source_key = ?2
`

type GetNewsletterSourceByKeyParams struct {
	Did       string `json:"did"`
	SourceKey string `json:"source_key"`
}

func (q *Queries) GetNewsletterSourceByKey(ctx context.Context, arg GetNewsletterSourceByKeyParams) (NewsletterSource, error) {
	row := q.db.QueryRowContext(ctx, getNewsletterSourceByKey, arg.Did, arg.SourceKey)
	var i NewsletterSource
	err := row.Scan(
		&i.ID,
		&i.Did,
		&i.SourceKey,
		&i.IdentityKind,
		&i.IdentityValue,
		&i.Title,
		&i.SenderName,
		&i.SenderAddress,
		&i.Status,
		&i.AcceptAfter,
		&i.IsPrimary,
		&i.Tags,
		&i.FirstReceivedAt,
		&i.LastReceivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNewsletterSourceWithStats = `-- name: GetNewsletterSourceWithStats :one
SELECT s.id, s.did, s.source_key, s.identity_kind, s.identity_value, s.title, s.sender_name, s.sender_address, s.status, s.accept_after, s.is_primary, s.tags, s.first_received_at, s.last_received_at, s.created_at, s.updated_at,
       (SELECT COUNT(*) FROM newsletter_messages m WHERE m.did = s.did AND m.source_id = s.id) AS issue_count,
       (SELECT COUNT(*) FROM newsletter_saves sv WHERE sv.did = s.did AND sv.message_id IN
           (SELECT id FROM newsletter_messages m WHERE m.did = s.did AND m.source_id = s.id)) AS saved_count,
       (SELECT COUNT(*) FROM newsletter_messages m WHERE m.did = s.did AND m.source_id = s.id AND m.received_at >= ?3 AND m.received_at < ?4) AS count_7d,
       (SELECT COUNT(*) FROM newsletter_messages m WHERE m.did = s.did AND m.source_id = s.id AND m.received_at >= ?5 AND m.received_at < ?4) AS count_28d,
       (SELECT COUNT(*) FROM newsletter_messages m WHERE m.did = s.did AND m.source_id = s.id AND m.received_at >= ?6 AND m.received_at < ?4) AS count_56d,
       (SELECT COUNT(*) FROM newsletter_messages m WHERE m.did = s.did AND m.source_id = s.id AND m.received_at >= ?7 AND m.received_at < ?4) AS count_84d
FROM newsletter_sources s
WHERE s.did = ?1 AND s.id = ?2
`

type GetNewsletterSourceWithStatsParams struct {
	Did          string `json:"did"`
	ID           string `json:"id"`
	ReceivedAt   string `json:"received_at"`
	ReceivedAt_2 string `json:"received_at_2"`
	ReceivedAt_3 string `json:"received_at_3"`
	ReceivedAt_4 string `json:"received_at_4"`
	ReceivedAt_5 string `json:"received_at_5"`
}

type GetNewsletterSourceWithStatsRow struct {
	ID              string  `json:"id"`
	Did             string  `json:"did"`
	SourceKey       string  `json:"source_key"`
	IdentityKind    string  `json:"identity_kind"`
	IdentityValue   *string `json:"identity_value"`
	Title           string  `json:"title"`
	SenderName      *string `json:"sender_name"`
	SenderAddress   string  `json:"sender_address"`
	Status          string  `json:"status"`
	AcceptAfter     *string `json:"accept_after"`
	IsPrimary       int64   `json:"is_primary"`
	Tags            string  `json:"tags"`
	FirstReceivedAt *string `json:"first_received_at"`
	LastReceivedAt  *string `json:"last_received_at"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
	IssueCount      int64   `json:"issue_count"`
	SavedCount      int64   `json:"saved_count"`
	Count7d         int64   `json:"count_7d"`
	Count28d        int64   `json:"count_28d"`
	Count56d        int64   `json:"count_56d"`
	Count84d        int64   `json:"count_84d"`
}

func (q *Queries) GetNewsletterSourceWithStats(ctx context.Context, arg GetNewsletterSourceWithStatsParams) (GetNewsletterSourceWithStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getNewsletterSourceWithStats,
		arg.Did,
		arg.ID,
		arg.ReceivedAt,
		arg.ReceivedAt_2,
		arg.ReceivedAt_3,
		arg.ReceivedAt_4,
		arg.ReceivedAt_5,
	)
	var i GetNewsletterSourceWithStatsRow
	err := row.Scan(
		&i.ID,
		&i.Did,
		&i.SourceKey,
		&i.IdentityKind,
		&i.IdentityValue,
		&i.Title,
		&i.SenderName,
		&i.SenderAddress,
		&i.Status,
		&i.AcceptAfter,
		&i.IsPrimary,
		&i.Tags,
		&i.FirstReceivedAt,
		&i.LastReceivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IssueCount,
		&i.SavedCount,
		&i.Count7d,
		&i.Count28d,
		&i.Count56d,
		&i.Count84d,
	)
	return i, err
}

const getNextNewsletterReceipt = `-- name: GetNextNewsletterReceipt :one
SELECT id, did, envelope_from, recipient, received_at, raw_mime,
       reserved_bytes, attempts, last_error, next_attempt_at, created_at
FROM newsletter_receipts
WHERE next_attempt_at IS NULL OR next_attempt_at <= ?1
ORDER BY created_at
LIMIT 1
`

func (q *Queries) GetNextNewsletterReceipt(ctx context.Context, nextAttemptAt *string) (NewsletterReceipt, error) {
	row := q.db.QueryRowContext(ctx, getNextNewsletterReceipt, nextAttemptAt)
	var i NewsletterReceipt
	err := row.Scan(
		&i.ID,
		&i.Did,
		&i.EnvelopeFrom,
		&i.Recipient,
		&i.ReceivedAt,
		&i.RawMime,
		&i.ReservedBytes,
		&i.Attempts,
		&i.LastError,
		&i.NextAttemptAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNewsletterMessagesForDigest = `-- name: ListNewsletterMessagesForDigest :many
SELECT m.id, m.did, m.source_id, m.entry_slug, m.dedupe_key, m.message_id, m.title, m.sender_name, m.sender_address, m.sent_at, m.received_at, m.body_html_blocked, m.body_html_remote, m.body_text, m.has_blocked_remote_images, m.remote_images_allowed, m.attachment_summary, m.storage_bytes, m.created_at, m.updated_at, s.title AS source_title, s.status AS source_status, s.is_primary AS source_primary,
       sv.id AS save_id, sv.created_at AS saved_at
FROM newsletter_messages m
JOIN newsletter_sources s ON s.id = m.source_id AND s.did = m.did
LEFT JOIN newsletter_saves sv ON sv.message_id = m.id AND sv.did = m.did
WHERE m.did = ?1 AND m.received_at >= ?2 AND m.received_at < ?3
  AND s.status = 'active'
ORDER BY m.received_at DESC, m.id DESC
`

type ListNewsletterMessagesForDigestParams struct {
	Did          string `json:"did"`
	ReceivedAt   string `json:"received_at"`
	ReceivedAt_2 string `json:"received_at_2"`
}

type ListNewsletterMessagesForDigestRow struct {
	ID                     string  `json:"id"`
	Did                    string  `json:"did"`
	SourceID               string  `json:"source_id"`
	EntrySlug              string  `json:"entry_slug"`
	DedupeKey              string  `json:"dedupe_key"`
	MessageID              *string `json:"message_id"`
	Title                  *string `json:"title"`
	SenderName             *string `json:"sender_name"`
	SenderAddress          string  `json:"sender_address"`
	SentAt                 *string `json:"sent_at"`
	ReceivedAt             string  `json:"received_at"`
	BodyHtmlBlocked        *string `json:"body_html_blocked"`
	BodyHtmlRemote         *string `json:"body_html_remote"`
	BodyText               *string `json:"body_text"`
	HasBlockedRemoteImages int64   `json:"has_blocked_remote_images"`
	RemoteImagesAllowed    int64   `json:"remote_images_allowed"`
	AttachmentSummary      *string `json:"attachment_summary"`
	StorageBytes           int64   `json:"storage_bytes"`
	CreatedAt              string  `json:"created_at"`
	UpdatedAt              string  `json:"updated_at"`
	SourceTitle            string  `json:"source_title"`
	SourceStatus           string  `json:"source_status"`
	SourcePrimary          int64   `json:"source_primary"`
	SaveID                 *string `json:"save_id"`
	SavedAt                *string `json:"saved_at"`
}

func (q *Queries) ListNewsletterMessagesForDigest(ctx context.Context, arg ListNewsletterMessagesForDigestParams) ([]ListNewsletterMessagesForDigestRow, error) {
	rows, err := q.db.QueryContext(ctx, listNewsletterMessagesForDigest, arg.Did, arg.ReceivedAt, arg.ReceivedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNewsletterMessagesForDigestRow
	for rows.Next() {
		var i ListNewsletterMessagesForDigestRow
		if err := rows.Scan(
			&i.ID,
			&i.Did,
			&i.SourceID,
			&i.EntrySlug,
			&i.DedupeKey,
			&i.MessageID,
			&i.Title,
			&i.SenderName,
			&i.SenderAddress,
			&i.SentAt,
			&i.ReceivedAt,
			&i.BodyHtmlBlocked,
			&i.BodyHtmlRemote,
			&i.BodyText,
			&i.HasBlockedRemoteImages,
			&i.RemoteImagesAllowed,
			&i.AttachmentSummary,
			&i.StorageBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceTitle,
			&i.SourceStatus,
			&i.SourcePrimary,
			&i.SaveID,
			&i.SavedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewsletterMessagesForSource = `-- name: ListNewsletterMessagesForSource :many
SELECT m.id, m.did, m.source_id, m.entry_slug, m.dedupe_key, m.message_id, m.title, m.sender_name, m.sender_address, m.sent_at, m.received_at, m.body_html_blocked, m.body_html_remote, m.body_text, m.has_blocked_remote_images, m.remote_images_allowed, m.attachment_summary, m.storage_bytes, m.created_at, m.updated_at, s.title AS source_title, s.status AS source_status, s.is_primary AS source_primary,
       sv.id AS save_id, sv.created_at AS saved_at
FROM newsletter_messages m
JOIN newsletter_sources s ON s.id = m.source_id AND s.did = m.did
LEFT JOIN newsletter_saves sv ON sv.message_id = m.id AND sv.did = m.did
WHERE m.did = ?1 AND m.source_id = ?2
ORDER BY m.received_at DESC, m.id DESC
`

type ListNewsletterMessagesForSourceParams struct {
	Did      string `json:"did"`
	SourceID string `json:"source_id"`
}

type ListNewsletterMessagesForSourceRow struct {
	ID                     string  `json:"id"`
	Did                    string  `json:"did"`
	SourceID               string  `json:"source_id"`
	EntrySlug              string  `json:"entry_slug"`
	DedupeKey              string  `json:"dedupe_key"`
	MessageID              *string `json:"message_id"`
	Title                  *string `json:"title"`
	SenderName             *string `json:"sender_name"`
	SenderAddress          string  `json:"sender_address"`
	SentAt                 *string `json:"sent_at"`
	ReceivedAt             string  `json:"received_at"`
	BodyHtmlBlocked        *string `json:"body_html_blocked"`
	BodyHtmlRemote         *string `json:"body_html_remote"`
	BodyText               *string `json:"body_text"`
	HasBlockedRemoteImages int64   `json:"has_blocked_remote_images"`
	RemoteImagesAllowed    int64   `json:"remote_images_allowed"`
	AttachmentSummary      *string `json:"attachment_summary"`
	StorageBytes           int64   `json:"storage_bytes"`
	CreatedAt              string  `json:"created_at"`
	UpdatedAt              string  `json:"updated_at"`
	SourceTitle            string  `json:"source_title"`
	SourceStatus           string  `json:"source_status"`
	SourcePrimary          int64   `json:"source_primary"`
	SaveID                 *string `json:"save_id"`
	SavedAt                *string `json:"saved_at"`
}

func (q *Queries) ListNewsletterMessagesForSource(ctx context.Context, arg ListNewsletterMessagesForSourceParams) ([]ListNewsletterMessagesForSourceRow, error) {
	rows, err := q.db.QueryContext(ctx, listNewsletterMessagesForSource, arg.Did, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNewsletterMessagesForSourceRow
	for rows.Next() {
		var i ListNewsletterMessagesForSourceRow
		if err := rows.Scan(
			&i.ID,
			&i.Did,
			&i.SourceID,
			&i.EntrySlug,
			&i.DedupeKey,
			&i.MessageID,
			&i.Title,
			&i.SenderName,
			&i.SenderAddress,
			&i.SentAt,
			&i.ReceivedAt,
			&i.BodyHtmlBlocked,
			&i.BodyHtmlRemote,
			&i.BodyText,
			&i.HasBlockedRemoteImages,
			&i.RemoteImagesAllowed,
			&i.AttachmentSummary,
			&i.StorageBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceTitle,
			&i.SourceStatus,
			&i.SourcePrimary,
			&i.SaveID,
			&i.SavedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewsletterSaves = `-- name: ListNewsletterSaves :many
SELECT sv.id, sv.did, sv.message_id, sv.created_at,
       m.entry_slug, m.title, m.received_at, src.title AS source_title
FROM newsletter_saves sv
JOIN newsletter_messages m ON m.id = sv.message_id AND m.did = sv.did
JOIN newsletter_sources src ON src.id = m.source_id AND src.did = m.did
WHERE sv.did = ?1
ORDER BY sv.created_at DESC, sv.id DESC
`

type ListNewsletterSavesRow struct {
	ID          string  `json:"id"`
	Did         string  `json:"did"`
	MessageID   string  `json:"message_id"`
	CreatedAt   string  `json:"created_at"`
	EntrySlug   string  `json:"entry_slug"`
	Title       *string `json:"title"`
	ReceivedAt  string  `json:"received_at"`
	SourceTitle string  `json:"source_title"`
}

func (q *Queries) ListNewsletterSaves(ctx context.Context, did string) ([]ListNewsletterSavesRow, error) {
	rows, err := q.db.QueryContext(ctx, listNewsletterSaves, did)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNewsletterSavesRow
	for rows.Next() {
		var i ListNewsletterSavesRow
		if err := rows.Scan(
			&i.ID,
			&i.Did,
			&i.MessageID,
			&i.CreatedAt,
			&i.EntrySlug,
			&i.Title,
			&i.ReceivedAt,
			&i.SourceTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewsletterSources = `-- name: ListNewsletterSources :many
SELECT s.id, s.did, s.source_key, s.identity_kind, s.identity_value, s.title, s.sender_name, s.sender_address, s.status, s.accept_after, s.is_primary, s.tags, s.first_received_at, s.last_received_at, s.created_at, s.updated_at,
       (SELECT COUNT(*) FROM newsletter_messages m WHERE m.did = s.did AND m.source_id = s.id) AS issue_count,
       (SELECT COUNT(*) FROM newsletter_saves sv WHERE sv.did = s.did AND sv.message_id IN
           (SELECT id FROM newsletter_messages m WHERE m.did = s.did AND m.source_id = s.id)) AS saved_count,
       (SELECT COUNT(*) FROM newsletter_messages m WHERE m.did = s.did AND m.source_id = s.id AND m.received_at >= ?2 AND m.received_at < ?3) AS count_7d,
       (SELECT COUNT(*) FROM newsletter_messages m WHERE m.did = s.did AND m.source_id = s.id AND m.received_at >= ?4 AND m.received_at < ?3) AS count_28d,
       (SELECT COUNT(*) FROM newsletter_messages m WHERE m.did = s.did AND m.source_id = s.id AND m.received_at >= ?5 AND m.received_at < ?3) AS count_56d,
       (SELECT COUNT(*) FROM newsletter_messages m WHERE m.did = s.did AND m.source_id = s.id AND m.received_at >= ?6 AND m.received_at < ?3) AS count_84d
FROM newsletter_sources s
WHERE s.did = ?1
ORDER BY s.title COLLATE NOCASE, s.id
`

type ListNewsletterSourcesParams struct {
	Did          string `json:"did"`
	ReceivedAt   string `json:"received_at"`
	ReceivedAt_2 string `json:"received_at_2"`
	ReceivedAt_3 string `json:"received_at_3"`
	ReceivedAt_4 string `json:"received_at_4"`
	ReceivedAt_5 string `json:"received_at_5"`
}

type ListNewsletterSourcesRow struct {
	ID              string  `json:"id"`
	Did             string  `json:"did"`
	SourceKey       string  `json:"source_key"`
	IdentityKind    string  `json:"identity_kind"`
	IdentityValue   *string `json:"identity_value"`
	Title           string  `json:"title"`
	SenderName      *string `json:"sender_name"`
	SenderAddress   string  `json:"sender_address"`
	Status          string  `json:"status"`
	AcceptAfter     *string `json:"accept_after"`
	IsPrimary       int64   `json:"is_primary"`
	Tags            string  `json:"tags"`
	FirstReceivedAt *string `json:"first_received_at"`
	LastReceivedAt  *string `json:"last_received_at"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
	IssueCount      int64   `json:"issue_count"`
	SavedCount      int64   `json:"saved_count"`
	Count7d         int64   `json:"count_7d"`
	Count28d        int64   `json:"count_28d"`
	Count56d        int64   `json:"count_56d"`
	Count84d        int64   `json:"count_84d"`
}

func (q *Queries) ListNewsletterSources(ctx context.Context, arg ListNewsletterSourcesParams) ([]ListNewsletterSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, listNewsletterSources,
		arg.Did,
		arg.ReceivedAt,
		arg.ReceivedAt_2,
		arg.ReceivedAt_3,
		arg.ReceivedAt_4,
		arg.ReceivedAt_5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNewsletterSourcesRow
	for rows.Next() {
		var i ListNewsletterSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Did,
			&i.SourceKey,
			&i.IdentityKind,
			&i.IdentityValue,
			&i.Title,
			&i.SenderName,
			&i.SenderAddress,
			&i.Status,
			&i.AcceptAfter,
			&i.IsPrimary,
			&i.Tags,
			&i.FirstReceivedAt,
			&i.LastReceivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IssueCount,
			&i.SavedCount,
			&i.Count7d,
			&i.Count28d,
			&i.Count56d,
			&i.Count84d,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNewsletterReceiptFailed = `-- name: MarkNewsletterReceiptFailed :exec
UPDATE newsletter_receipts
SET attempts = attempts + 1, last_error = ?2, next_attempt_at = ?3
WHERE id = ?1
`

type MarkNewsletterReceiptFailedParams struct {
	ID            string  `json:"id"`
	LastError     *string `json:"last_error"`
	NextAttemptAt *string `json:"next_attempt_at"`
}

func (q *Queries) MarkNewsletterReceiptFailed(ctx context.Context, arg MarkNewsletterReceiptFailedParams) error {
	_, err := q.db.ExecContext(ctx, markNewsletterReceiptFailed, arg.ID, arg.LastError, arg.NextAttemptAt)
	return err
}

const moveNewsletterMessage = `-- name: MoveNewsletterMessage :exec
UPDATE newsletter_messages SET source_id = ?3, updated_at = ?4
WHERE did = ?1 AND id = ?2
`

type MoveNewsletterMessageParams struct {
	Did       string `json:"did"`
	ID        string `json:"id"`
	SourceID  string `json:"source_id"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) MoveNewsletterMessage(ctx context.Context, arg MoveNewsletterMessageParams) error {
	_, err := q.db.ExecContext(ctx, moveNewsletterMessage,
		arg.Did,
		arg.ID,
		arg.SourceID,
		arg.UpdatedAt,
	)
	return err
}

const patchNewsletterSource = `-- name: PatchNewsletterSource :exec
UPDATE newsletter_sources
SET title = ?3, is_primary = ?4, tags = ?5, updated_at = ?6
WHERE did = ?1 AND id = ?2
`

type PatchNewsletterSourceParams struct {
	Did       string `json:"did"`
	ID        string `json:"id"`
	Title     string `json:"title"`
	IsPrimary int64  `json:"is_primary"`
	Tags      string `json:"tags"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) PatchNewsletterSource(ctx context.Context, arg PatchNewsletterSourceParams) error {
	_, err := q.db.ExecContext(ctx, patchNewsletterSource,
		arg.Did,
		arg.ID,
		arg.Title,
		arg.IsPrimary,
		arg.Tags,
		arg.UpdatedAt,
	)
	return err
}

const setNewsletterSourceStatus = `-- name: SetNewsletterSourceStatus :exec
UPDATE newsletter_sources SET status = ?3, updated_at = ?4
WHERE did = ?1 AND id = ?2
`

type SetNewsletterSourceStatusParams struct {
	Did       string `json:"did"`
	ID        string `json:"id"`
	Status    string `json:"status"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) SetNewsletterSourceStatus(ctx context.Context, arg SetNewsletterSourceStatusParams) error {
	_, err := q.db.ExecContext(ctx, setNewsletterSourceStatus,
		arg.Did,
		arg.ID,
		arg.Status,
		arg.UpdatedAt,
	)
	return err
}

const touchNewsletterSource = `-- name: TouchNewsletterSource :exec
UPDATE newsletter_sources
SET sender_name = COALESCE(?1, sender_name),
    sender_address = CASE WHEN ?2 = '' THEN sender_address ELSE ?2 END,
    first_received_at = COALESCE(first_received_at, ?3),
    last_received_at = ?3,
    updated_at = ?3
WHERE did = ?4 AND id = ?5
`

type TouchNewsletterSourceParams struct {
	SenderName    *string     `json:"sender_name"`
	SenderAddress interface{} `json:"sender_address"`
	ReceivedAt    *string     `json:"received_at"`
	Did           string      `json:"did"`
	ID            string      `json:"id"`
}

func (q *Queries) TouchNewsletterSource(ctx context.Context, arg TouchNewsletterSourceParams) error {
	_, err := q.db.ExecContext(ctx, touchNewsletterSource,
		arg.SenderName,
		arg.SenderAddress,
		arg.ReceivedAt,
		arg.Did,
		arg.ID,
	)
	return err
}
