// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package db

import (
	"context"
)

const deleteAuthRequest = `-- name: DeleteAuthRequest :exec
DELETE FROM oauth_auth_requests
WHERE state = ?
`

func (q *Queries) DeleteAuthRequest(ctx context.Context, state string) error {
	_, err := q.db.ExecContext(ctx, deleteAuthRequest, state)
	return err
}

const deleteExpiredAuthRequests = `-- name: DeleteExpiredAuthRequests :execrows
DELETE FROM oauth_auth_requests
WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredAuthRequests(ctx context.Context, expiresAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredAuthRequests, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM oauth_sessions
WHERE did = ? AND session_id = ?
`

type DeleteSessionParams struct {
	Did       string `json:"did"`
	SessionID string `json:"session_id"`
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) error {
	_, err := q.db.ExecContext(ctx, deleteSession, arg.Did, arg.SessionID)
	return err
}

const getAuthRequest = `-- name: GetAuthRequest :one
SELECT data, expires_at FROM oauth_auth_requests
WHERE state = ?
`

type GetAuthRequestRow struct {
	Data      []byte `json:"data"`
	ExpiresAt string `json:"expires_at"`
}

func (q *Queries) GetAuthRequest(ctx context.Context, state string) (GetAuthRequestRow, error) {
	row := q.db.QueryRowContext(ctx, getAuthRequest, state)
	var i GetAuthRequestRow
	err := row.Scan(&i.Data, &i.ExpiresAt)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT data FROM oauth_sessions
WHERE did = ? AND session_id = ?
`

type GetSessionParams struct {
	Did       string `json:"did"`
	SessionID string `json:"session_id"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getSession, arg.Did, arg.SessionID)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const putAuthRequest = `-- name: PutAuthRequest :exec
INSERT INTO oauth_auth_requests (state, data, created_at, expires_at)
VALUES (?, ?, ?, ?)
`

type PutAuthRequestParams struct {
	State     string `json:"state"`
	Data      []byte `json:"data"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
}

func (q *Queries) PutAuthRequest(ctx context.Context, arg PutAuthRequestParams) error {
	_, err := q.db.ExecContext(ctx, putAuthRequest,
		arg.State,
		arg.Data,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const putSession = `-- name: PutSession :exec
INSERT INTO oauth_sessions (did, session_id, data, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (did, session_id) DO UPDATE SET
    data = excluded.data,
    updated_at = excluded.updated_at
`

type PutSessionParams struct {
	Did       string `json:"did"`
	SessionID string `json:"session_id"`
	Data      []byte `json:"data"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) PutSession(ctx context.Context, arg PutSessionParams) error {
	_, err := q.db.ExecContext(ctx, putSession,
		arg.Did,
		arg.SessionID,
		arg.Data,
		arg.UpdatedAt,
	)
	return err
}
