// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: person_search.sql

package db

import (
	"context"
	"strings"
)

const personSearchPresence = `-- name: PersonSearchPresence :many
SELECT DISTINCT repo_did FROM discover_trending_signals
WHERE repo_did IN (/*SLICE:dids*/?) AND signal_kind != 'save'
`

// Reader-network presence for a batch of AppView typeahead DIDs (SPEC
// <discovery> People "Search" + "Eligibility"). Returns only the DIDs that
// have at least one non-save signal row; the caller folds the result into a
// map[string]bool, so a DID absent from the result is absent from the network.
// signal_kind != 'save' is the save-privacy invariant: a save-only person must
// not badge, or the badge would leak that they save (SPEC <discovery> People
// "Eligibility": "Saves don't confer eligibility").
//
// Uses sqlc.slice for a single batched read. The repo has never used
// sqlc.slice before; if `make sqlc` mishandles it, switch the caller to
// PersonSearchPresenceOne below, called once per DID (typeahead is capped at
// ~10 results, so the sequential cost is trivial).
func (q *Queries) PersonSearchPresence(ctx context.Context, dids []string) ([]string, error) {
	query := personSearchPresence
	var queryParams []interface{}
	if len(dids) > 0 {
		for _, v := range dids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:dids*/?", strings.Repeat(",?", len(dids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:dids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var repo_did string
		if err := rows.Scan(&repo_did); err != nil {
			return nil, err
		}
		items = append(items, repo_did)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const personSearchPresenceOne = `-- name: PersonSearchPresenceOne :one
SELECT EXISTS(
    SELECT 1 FROM discover_trending_signals
    WHERE repo_did = ? AND signal_kind != 'save'
) AS present
`

// Per-DID fallback for PersonSearchPresence when sqlc.slice codegen misbehaves;
// same save-free presence test, called sequentially over the <=10 hits.
func (q *Queries) PersonSearchPresenceOne(ctx context.Context, repoDid string) (bool, error) {
	row := q.db.QueryRowContext(ctx, personSearchPresenceOne, repoDid)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const personSearchTasteHints = `-- name: PersonSearchTasteHints :many
SELECT title FROM discover_trending_signals
WHERE repo_did = ?
  AND signal_kind IN ('subscribe', 'author')
  AND title IS NOT NULL AND title != ''
GROUP BY title
ORDER BY MAX(signal_at) DESC, title ASC
LIMIT ?
`

type PersonSearchTasteHintsParams struct {
	RepoDid string `json:"repo_did"`
	Limit   int64  `json:"limit"`
}

// Up to `limit` publication titles for a present person's search badge (SPEC
// <discovery> People "Search"). Drawn from subscribe/author signal rows only:
// never 'share', never 'save'. A taste hint previews what the person reads or
// publishes, and save rows are invisible under save privacy. Distinct titles,
// most-recent signal first with a title tiebreak so the pick is deterministic.
func (q *Queries) PersonSearchTasteHints(ctx context.Context, arg PersonSearchTasteHintsParams) ([]*string, error) {
	rows, err := q.db.QueryContext(ctx, personSearchTasteHints, arg.RepoDid, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var title *string
		if err := rows.Scan(&title); err != nil {
			return nil, err
		}
		items = append(items, title)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
