// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AllowNewsletterRemoteImages(ctx context.Context, arg AllowNewsletterRemoteImagesParams) error
	CreateManualNewsletterSource(ctx context.Context, arg CreateManualNewsletterSourceParams) error
	CreateNewsletterAddress(ctx context.Context, arg CreateNewsletterAddressParams) error
	CreateNewsletterInlineAsset(ctx context.Context, arg CreateNewsletterInlineAssetParams) error
	CreateNewsletterMessage(ctx context.Context, arg CreateNewsletterMessageParams) (string, error)
	CreateNewsletterReceipt(ctx context.Context, arg CreateNewsletterReceiptParams) error
	CreateNewsletterSave(ctx context.Context, arg CreateNewsletterSaveParams) error
	CreateNewsletterSource(ctx context.Context, arg CreateNewsletterSourceParams) error
	DeleteAuthRequest(ctx context.Context, state string) error
	DeleteExpiredAuthRequests(ctx context.Context, expiresAt string) (int64, error)
	DeleteFeedEntry(ctx context.Context, arg DeleteFeedEntryParams) error
	DeleteNewsletterReceipt(ctx context.Context, id string) error
	DeleteNewsletterSave(ctx context.Context, arg DeleteNewsletterSaveParams) error
	DeleteSession(ctx context.Context, arg DeleteSessionParams) error
	DeleteStoppedUnsavedNewsletterMessage(ctx context.Context, arg DeleteStoppedUnsavedNewsletterMessageParams) error
	DeleteUnsavedNewsletterMessages(ctx context.Context, arg DeleteUnsavedNewsletterMessagesParams) error
	DeleteUserSave(ctx context.Context, arg DeleteUserSaveParams) error
	DeleteUserSubscription(ctx context.Context, arg DeleteUserSubscriptionParams) error
	EnableNewsletterSource(ctx context.Context, arg EnableNewsletterSourceParams) error
	GetAuthRequest(ctx context.Context, state string) (GetAuthRequestRow, error)
	// Column order matches the table's physical layout so sqlc reuses the Feed
	// model instead of minting a one-off row type.
	GetFeed(ctx context.Context, feedUrl string) (Feed, error)
	GetFeedEntryBySlug(ctx context.Context, entrySlug string) (FeedEntry, error)
	// Returns the stored icon URL for a feed. Drives the favicon-proxy SSRF guard:
	// the proxy only streams URLs the sync pipeline has already vetted.
	GetFeedIconURL(ctx context.Context, feedUrl string) (*string, error)
	GetNewsletterAddress(ctx context.Context, did string) (NewsletterAddress, error)
	GetNewsletterAddressByLocalPart(ctx context.Context, localPart string) (NewsletterAddress, error)
	GetNewsletterGlobalStorageBytes(ctx context.Context) (int64, error)
	GetNewsletterInlineAsset(ctx context.Context, arg GetNewsletterInlineAssetParams) (NewsletterInlineAsset, error)
	GetNewsletterMessage(ctx context.Context, arg GetNewsletterMessageParams) (GetNewsletterMessageRow, error)
	GetNewsletterMessageBySlug(ctx context.Context, arg GetNewsletterMessageBySlugParams) (GetNewsletterMessageBySlugRow, error)
	GetNewsletterOwnerStorageBytes(ctx context.Context, did string) (int64, error)
	GetNewsletterSave(ctx context.Context, arg GetNewsletterSaveParams) (NewsletterSafe, error)
	GetNewsletterSaveForMessage(ctx context.Context, arg GetNewsletterSaveForMessageParams) (NewsletterSafe, error)
	GetNewsletterSource(ctx context.Context, arg GetNewsletterSourceParams) (NewsletterSource, error)
	GetNewsletterSourceByKey(ctx context.Context, arg GetNewsletterSourceByKeyParams) (NewsletterSource, error)
	GetNewsletterSourceWithStats(ctx context.Context, arg GetNewsletterSourceWithStatsParams) (GetNewsletterSourceWithStatsRow, error)
	GetNextNewsletterReceipt(ctx context.Context, nextAttemptAt *string) (NewsletterReceipt, error)
	GetSession(ctx context.Context, arg GetSessionParams) ([]byte, error)
	GetUserSave(ctx context.Context, arg GetUserSaveParams) (UserSave, error)
	GetUserSaveByItemURL(ctx context.Context, arg GetUserSaveByItemURLParams) (UserSave, error)
	// Single-source counterpart to ListUserSourcesWithStats, keyed by (did, rkey).
	// Carries the same windowed counts plus total_entries and saved_by_you so the
	// source detail page can render its stat row in one query.
	GetUserSourceWithStats(ctx context.Context, arg GetUserSourceWithStatsParams) (GetUserSourceWithStatsRow, error)
	GetUserSubscription(ctx context.Context, arg GetUserSubscriptionParams) (UserSubscription, error)
	GetUserSubscriptionByFeedURL(ctx context.Context, arg GetUserSubscriptionByFeedURLParams) (UserSubscription, error)
	ListAllFeedURLs(ctx context.Context) ([]string, error)
	ListDigestForUser(ctx context.Context, arg ListDigestForUserParams) ([]ListDigestForUserRow, error)
	// Entries from a single feed, newest first, bounded by limit. The join to
	// user_subscriptions doubles as an ownership filter; the handler still
	// distinguishes "not subscribed" from "no posts" via a separate lookup.
	ListEntriesForSource(ctx context.Context, arg ListEntriesForSourceParams) ([]ListEntriesForSourceRow, error)
	ListFeedEntriesForDiff(ctx context.Context, feedUrl string) ([]ListFeedEntriesForDiffRow, error)
	ListFeedURLsForUser(ctx context.Context, did string) ([]string, error)
	ListNewsletterMessagesForDigest(ctx context.Context, arg ListNewsletterMessagesForDigestParams) ([]ListNewsletterMessagesForDigestRow, error)
	ListNewsletterMessagesForSource(ctx context.Context, arg ListNewsletterMessagesForSourceParams) ([]ListNewsletterMessagesForSourceRow, error)
	ListNewsletterSaves(ctx context.Context, did string) ([]ListNewsletterSavesRow, error)
	ListNewsletterSources(ctx context.Context, arg ListNewsletterSourcesParams) ([]ListNewsletterSourcesRow, error)
	// Newest first. The entry join resolves title/slug/target for saves whose entry
	// is still cached; url is not unique in feed_entries, so the newest matching
	// entry is picked by id rather than joined on url directly, which would fan one
	// save out into a row per feed carrying the same link.
	ListUserSaves(ctx context.Context, did string) ([]ListUserSavesRow, error)
	// Snapshot of a user's local save index, used by sync_user to diff against the
	// PDS and reconcile inserts/deletes.
	ListUserSavesForSync(ctx context.Context, did string) ([]ListUserSavesForSyncRow, error)
	// One row per subscription with feed metadata and windowed entry stats. The
	// four window cutoffs (7d, 28d, 56d, 84d as ISO timestamps) and "now" are
	// passed in by the handler so all rows share a single clock.
	ListUserSourcesWithStats(ctx context.Context, arg ListUserSourcesWithStatsParams) ([]ListUserSourcesWithStatsRow, error)
	// Ordered by rkey (a TID, so creation order) to make "first-seen casing wins"
	// deterministic across a tag case-collision.
	ListUserSubscriptionTags(ctx context.Context, did string) ([]*string, error)
	ListUserSubscriptions(ctx context.Context, did string) ([]UserSubscription, error)
	ListUserSubscriptionsForSync(ctx context.Context, did string) ([]ListUserSubscriptionsForSyncRow, error)
	// Sibling-guard read: every subscription with its catalog site_url so the
	// resolve handler can flag candidates that point at the same site under the
	// other kind (rss vs standardfeed).
	ListUserSubscriptionsWithSiteURL(ctx context.Context, did string) ([]ListUserSubscriptionsWithSiteURLRow, error)
	MarkNewsletterReceiptFailed(ctx context.Context, arg MarkNewsletterReceiptFailedParams) error
	MoveNewsletterMessage(ctx context.Context, arg MoveNewsletterMessageParams) error
	PatchNewsletterSource(ctx context.Context, arg PatchNewsletterSourceParams) error
	PutAuthRequest(ctx context.Context, arg PutAuthRequestParams) error
	PutSession(ctx context.Context, arg PutSessionParams) error
	SetFeedIconURL(ctx context.Context, arg SetFeedIconURLParams) error
	SetNewsletterSourceStatus(ctx context.Context, arg SetNewsletterSourceStatusParams) error
	TouchNewsletterSource(ctx context.Context, arg TouchNewsletterSourceParams) error
	UpdateFeedEntryExtractedBody(ctx context.Context, arg UpdateFeedEntryExtractedBodyParams) error
	// SPEC <feed-sources> failure handling; success (UpdateFeedFetchState) resets both.
	UpdateFeedFetchFailure(ctx context.Context, arg UpdateFeedFetchFailureParams) error
	// SPEC <feed-sources> failure handling: success resets the backoff counter and clears the skip stamp.
	UpdateFeedFetchState(ctx context.Context, arg UpdateFeedFetchStateParams) error
	// kind defaults to 'rss' via NULLIF so pre-standardfeed callers passing the
	// zero value keep working; it is never changed on conflict. title is the
	// cached publication name; COALESCE keeps rss callers (nil) from clobbering it.
	// All params are named (not positional): mixing sqlc.arg() with bare ? makes
	// sqlc emit non-contiguous placeholder numbers that modernc.org/sqlite can't
	// bind ("missing argument with index N").
	UpsertFeed(ctx context.Context, arg UpsertFeedParams) error
	UpsertFeedEntry(ctx context.Context, arg UpsertFeedEntryParams) error
	// Standardfeed counterpart to UpsertFeedEntry. Unlike the rss upsert it owns
	// extracted_body and record_cid on conflict: a CID change must reset the
	// cached readability body (path-ful docs pass NULL) or refresh the plaintext
	// fallback (path-less docs pass the new textContent).
	UpsertStandardfeedEntry(ctx context.Context, arg UpsertStandardfeedEntryParams) error
	UpsertUserSave(ctx context.Context, arg UpsertUserSaveParams) error
	// Fully named params (see UpsertFeed): avoids the mixed named/positional
	// numbering that breaks binding under modernc.org/sqlite.
	UpsertUserSubscription(ctx context.Context, arg UpsertUserSubscriptionParams) error
}

var _ Querier = (*Queries)(nil)
