// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	DeleteAuthRequest(ctx context.Context, state string) error
	DeleteExpiredAuthRequests(ctx context.Context, expiresAt string) (int64, error)
	DeleteSession(ctx context.Context, arg DeleteSessionParams) error
	DeleteUserSave(ctx context.Context, arg DeleteUserSaveParams) error
	DeleteUserSubscription(ctx context.Context, arg DeleteUserSubscriptionParams) error
	GetAuthRequest(ctx context.Context, state string) (GetAuthRequestRow, error)
	GetFeed(ctx context.Context, feedUrl string) (Feed, error)
	GetFeedEntryBySlug(ctx context.Context, entrySlug string) (FeedEntry, error)
	GetSession(ctx context.Context, arg GetSessionParams) ([]byte, error)
	GetUserSave(ctx context.Context, arg GetUserSaveParams) (UserSave, error)
	GetUserSaveByItemURL(ctx context.Context, arg GetUserSaveByItemURLParams) (UserSave, error)
	GetUserSubscription(ctx context.Context, arg GetUserSubscriptionParams) (UserSubscription, error)
	GetUserSubscriptionByFeedURL(ctx context.Context, arg GetUserSubscriptionByFeedURLParams) (UserSubscription, error)
	ListAllEntriesForUser(ctx context.Context, did string) ([]ListAllEntriesForUserRow, error)
	ListDigestForUser(ctx context.Context, arg ListDigestForUserParams) ([]ListDigestForUserRow, error)
	ListFeedURLsForUser(ctx context.Context, did string) ([]string, error)
	// One row per subscription with feed metadata and windowed entry stats. The
	// four window cutoffs (7d, 28d, 56d, 84d as ISO timestamps) and "now" are
	// passed in by the handler so all rows share a single clock.
	ListUserSourcesWithStats(ctx context.Context, arg ListUserSourcesWithStatsParams) ([]ListUserSourcesWithStatsRow, error)
	ListUserSubscriptions(ctx context.Context, did string) ([]UserSubscription, error)
	ListUserSubscriptionsForSync(ctx context.Context, did string) ([]ListUserSubscriptionsForSyncRow, error)
	PutAuthRequest(ctx context.Context, arg PutAuthRequestParams) error
	PutSession(ctx context.Context, arg PutSessionParams) error
	SetFeedIconURL(ctx context.Context, arg SetFeedIconURLParams) error
	UpdateFeedEntryExtractedBody(ctx context.Context, arg UpdateFeedEntryExtractedBodyParams) error
	UpdateFeedFetchState(ctx context.Context, arg UpdateFeedFetchStateParams) error
	UpsertFeed(ctx context.Context, arg UpsertFeedParams) error
	UpsertFeedEntry(ctx context.Context, arg UpsertFeedEntryParams) error
	UpsertUserSave(ctx context.Context, arg UpsertUserSaveParams) error
	UpsertUserSubscription(ctx context.Context, arg UpsertUserSubscriptionParams) error
}

var _ Querier = (*Queries)(nil)
