// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saves.sql

package db

import (
	"context"
)

const deleteUserSave = `-- name: DeleteUserSave :exec
DELETE FROM user_saves WHERE did = ? AND rkey = ?
`

type DeleteUserSaveParams struct {
	Did  string `json:"did"`
	Rkey string `json:"rkey"`
}

func (q *Queries) DeleteUserSave(ctx context.Context, arg DeleteUserSaveParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserSave, arg.Did, arg.Rkey)
	return err
}

const getUserSave = `-- name: GetUserSave :one
SELECT did, rkey, at_uri, item_url, feed_url, created_at, updated_at
FROM user_saves WHERE did = ? AND rkey = ?
`

type GetUserSaveParams struct {
	Did  string `json:"did"`
	Rkey string `json:"rkey"`
}

func (q *Queries) GetUserSave(ctx context.Context, arg GetUserSaveParams) (UserSave, error) {
	row := q.db.QueryRowContext(ctx, getUserSave, arg.Did, arg.Rkey)
	var i UserSave
	err := row.Scan(
		&i.Did,
		&i.Rkey,
		&i.AtUri,
		&i.ItemUrl,
		&i.FeedUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSaveByItemURL = `-- name: GetUserSaveByItemURL :one
SELECT did, rkey, at_uri, item_url, feed_url, created_at, updated_at
FROM user_saves WHERE did = ? AND item_url = ?
`

type GetUserSaveByItemURLParams struct {
	Did     string `json:"did"`
	ItemUrl string `json:"item_url"`
}

func (q *Queries) GetUserSaveByItemURL(ctx context.Context, arg GetUserSaveByItemURLParams) (UserSave, error) {
	row := q.db.QueryRowContext(ctx, getUserSaveByItemURL, arg.Did, arg.ItemUrl)
	var i UserSave
	err := row.Scan(
		&i.Did,
		&i.Rkey,
		&i.AtUri,
		&i.ItemUrl,
		&i.FeedUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserSaves = `-- name: ListUserSaves :many
SELECT
    s.did, s.rkey, s.at_uri, s.item_url, s.feed_url, s.created_at, s.updated_at,
    e.title AS entry_title,
    e.entry_slug AS entry_slug,
    e.url AS entry_url,
    e.feed_url AS entry_feed_url
FROM user_saves s
LEFT JOIN feed_entries e ON e.id = (
    SELECT id FROM feed_entries WHERE url = s.item_url ORDER BY published_at DESC LIMIT 1
)
WHERE s.did = ?
ORDER BY s.created_at DESC, s.rkey DESC
`

type ListUserSavesRow struct {
	Did          string  `json:"did"`
	Rkey         string  `json:"rkey"`
	AtUri        string  `json:"at_uri"`
	ItemUrl      string  `json:"item_url"`
	FeedUrl      *string `json:"feed_url"`
	CreatedAt    string  `json:"created_at"`
	UpdatedAt    string  `json:"updated_at"`
	EntryTitle   *string `json:"entry_title"`
	EntrySlug    *string `json:"entry_slug"`
	EntryUrl     *string `json:"entry_url"`
	EntryFeedUrl *string `json:"entry_feed_url"`
}

// Newest first. The entry join resolves title/slug/target for saves whose entry
// is still cached; url is not unique in feed_entries, so the newest matching
// entry is picked by id rather than joined on url directly, which would fan one
// save out into a row per feed carrying the same link.
func (q *Queries) ListUserSaves(ctx context.Context, did string) ([]ListUserSavesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserSaves, did)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSavesRow
	for rows.Next() {
		var i ListUserSavesRow
		if err := rows.Scan(
			&i.Did,
			&i.Rkey,
			&i.AtUri,
			&i.ItemUrl,
			&i.FeedUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EntryTitle,
			&i.EntrySlug,
			&i.EntryUrl,
			&i.EntryFeedUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSavesForSync = `-- name: ListUserSavesForSync :many
SELECT did, rkey, at_uri, item_url, feed_url, created_at FROM user_saves WHERE did = ?
`

type ListUserSavesForSyncRow struct {
	Did       string  `json:"did"`
	Rkey      string  `json:"rkey"`
	AtUri     string  `json:"at_uri"`
	ItemUrl   string  `json:"item_url"`
	FeedUrl   *string `json:"feed_url"`
	CreatedAt string  `json:"created_at"`
}

// Snapshot of a user's local save index, used by sync_user to diff against the
// PDS and reconcile inserts/deletes.
func (q *Queries) ListUserSavesForSync(ctx context.Context, did string) ([]ListUserSavesForSyncRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserSavesForSync, did)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSavesForSyncRow
	for rows.Next() {
		var i ListUserSavesForSyncRow
		if err := rows.Scan(
			&i.Did,
			&i.Rkey,
			&i.AtUri,
			&i.ItemUrl,
			&i.FeedUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserSave = `-- name: UpsertUserSave :exec
INSERT INTO user_saves (
    did, rkey, at_uri, item_url, feed_url, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (did, rkey) DO UPDATE SET
    at_uri     = excluded.at_uri,
    item_url   = excluded.item_url,
    feed_url   = excluded.feed_url,
    updated_at = excluded.updated_at
`

type UpsertUserSaveParams struct {
	Did       string  `json:"did"`
	Rkey      string  `json:"rkey"`
	AtUri     string  `json:"at_uri"`
	ItemUrl   string  `json:"item_url"`
	FeedUrl   *string `json:"feed_url"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
}

func (q *Queries) UpsertUserSave(ctx context.Context, arg UpsertUserSaveParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserSave,
		arg.Did,
		arg.Rkey,
		arg.AtUri,
		arg.ItemUrl,
		arg.FeedUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
