// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shares.sql

package db

import (
	"context"
)

const deleteUserShare = `-- name: DeleteUserShare :exec
DELETE FROM user_shares WHERE did = ? AND rkey = ?
`

type DeleteUserShareParams struct {
	Did  string `json:"did"`
	Rkey string `json:"rkey"`
}

func (q *Queries) DeleteUserShare(ctx context.Context, arg DeleteUserShareParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserShare, arg.Did, arg.Rkey)
	return err
}

const getUserShare = `-- name: GetUserShare :one
SELECT did, rkey, at_uri, kind, item_url, document, comment, feed_url, sidecar_rkey, created_at, updated_at
FROM user_shares WHERE did = ? AND rkey = ?
`

type GetUserShareParams struct {
	Did  string `json:"did"`
	Rkey string `json:"rkey"`
}

func (q *Queries) GetUserShare(ctx context.Context, arg GetUserShareParams) (UserShare, error) {
	row := q.db.QueryRowContext(ctx, getUserShare, arg.Did, arg.Rkey)
	var i UserShare
	err := row.Scan(
		&i.Did,
		&i.Rkey,
		&i.AtUri,
		&i.Kind,
		&i.ItemUrl,
		&i.Document,
		&i.Comment,
		&i.FeedUrl,
		&i.SidecarRkey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserShareByDocument = `-- name: GetUserShareByDocument :one
SELECT did, rkey, at_uri, kind, item_url, document, comment, feed_url, sidecar_rkey, created_at, updated_at
FROM user_shares WHERE did = ? AND document = ?
`

type GetUserShareByDocumentParams struct {
	Did      string  `json:"did"`
	Document *string `json:"document"`
}

func (q *Queries) GetUserShareByDocument(ctx context.Context, arg GetUserShareByDocumentParams) (UserShare, error) {
	row := q.db.QueryRowContext(ctx, getUserShareByDocument, arg.Did, arg.Document)
	var i UserShare
	err := row.Scan(
		&i.Did,
		&i.Rkey,
		&i.AtUri,
		&i.Kind,
		&i.ItemUrl,
		&i.Document,
		&i.Comment,
		&i.FeedUrl,
		&i.SidecarRkey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserShareByItemURL = `-- name: GetUserShareByItemURL :one
SELECT did, rkey, at_uri, kind, item_url, document, comment, feed_url, sidecar_rkey, created_at, updated_at
FROM user_shares WHERE did = ? AND item_url = ? AND kind = 'rss'
`

type GetUserShareByItemURLParams struct {
	Did     string  `json:"did"`
	ItemUrl *string `json:"item_url"`
}

// Dedupe probe for rss shares; standardfeed shares dedupe by document instead.
func (q *Queries) GetUserShareByItemURL(ctx context.Context, arg GetUserShareByItemURLParams) (UserShare, error) {
	row := q.db.QueryRowContext(ctx, getUserShareByItemURL, arg.Did, arg.ItemUrl)
	var i UserShare
	err := row.Scan(
		&i.Did,
		&i.Rkey,
		&i.AtUri,
		&i.Kind,
		&i.ItemUrl,
		&i.Document,
		&i.Comment,
		&i.FeedUrl,
		&i.SidecarRkey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserShares = `-- name: ListUserShares :many
SELECT
    s.did, s.rkey, s.at_uri, s.kind, s.item_url, s.document, s.comment,
    s.feed_url, s.sidecar_rkey, s.created_at, s.updated_at,
    e.title AS entry_title,
    e.entry_slug AS entry_slug
FROM user_shares s
LEFT JOIN feed_entries e ON e.guid = s.document
WHERE s.did = ?
ORDER BY s.created_at DESC, s.rkey DESC
`

type ListUserSharesRow struct {
	Did         string  `json:"did"`
	Rkey        string  `json:"rkey"`
	AtUri       string  `json:"at_uri"`
	Kind        string  `json:"kind"`
	ItemUrl     *string `json:"item_url"`
	Document    *string `json:"document"`
	Comment     *string `json:"comment"`
	FeedUrl     *string `json:"feed_url"`
	SidecarRkey *string `json:"sidecar_rkey"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
	EntryTitle  *string `json:"entry_title"`
	EntrySlug   *string `json:"entry_slug"`
}

// Newest first. The entry join resolves title/slug for document shares whose
// entry is still cached; deleted entries fall back to item_url display.
func (q *Queries) ListUserShares(ctx context.Context, did string) ([]ListUserSharesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserShares, did)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSharesRow
	for rows.Next() {
		var i ListUserSharesRow
		if err := rows.Scan(
			&i.Did,
			&i.Rkey,
			&i.AtUri,
			&i.Kind,
			&i.ItemUrl,
			&i.Document,
			&i.Comment,
			&i.FeedUrl,
			&i.SidecarRkey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EntryTitle,
			&i.EntrySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSharesForSync = `-- name: ListUserSharesForSync :many
SELECT did, rkey, at_uri, kind, item_url, document, sidecar_rkey, created_at FROM user_shares WHERE did = ?
`

type ListUserSharesForSyncRow struct {
	Did         string  `json:"did"`
	Rkey        string  `json:"rkey"`
	AtUri       string  `json:"at_uri"`
	Kind        string  `json:"kind"`
	ItemUrl     *string `json:"item_url"`
	Document    *string `json:"document"`
	SidecarRkey *string `json:"sidecar_rkey"`
	CreatedAt   string  `json:"created_at"`
}

// Snapshot of a user's local share index, used by sync_user to diff against
// the PDS and reconcile inserts/deletes.
func (q *Queries) ListUserSharesForSync(ctx context.Context, did string) ([]ListUserSharesForSyncRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserSharesForSync, did)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSharesForSyncRow
	for rows.Next() {
		var i ListUserSharesForSyncRow
		if err := rows.Scan(
			&i.Did,
			&i.Rkey,
			&i.AtUri,
			&i.Kind,
			&i.ItemUrl,
			&i.Document,
			&i.SidecarRkey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserShare = `-- name: UpsertUserShare :exec
INSERT INTO user_shares (
    did, rkey, at_uri, kind, item_url, document, comment, feed_url, sidecar_rkey, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (did, rkey) DO UPDATE SET
    at_uri       = excluded.at_uri,
    kind         = excluded.kind,
    item_url     = excluded.item_url,
    document     = excluded.document,
    comment      = excluded.comment,
    feed_url     = excluded.feed_url,
    sidecar_rkey = excluded.sidecar_rkey,
    updated_at   = excluded.updated_at
`

type UpsertUserShareParams struct {
	Did         string  `json:"did"`
	Rkey        string  `json:"rkey"`
	AtUri       string  `json:"at_uri"`
	Kind        string  `json:"kind"`
	ItemUrl     *string `json:"item_url"`
	Document    *string `json:"document"`
	Comment     *string `json:"comment"`
	FeedUrl     *string `json:"feed_url"`
	SidecarRkey *string `json:"sidecar_rkey"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
}

func (q *Queries) UpsertUserShare(ctx context.Context, arg UpsertUserShareParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserShare,
		arg.Did,
		arg.Rkey,
		arg.AtUri,
		arg.Kind,
		arg.ItemUrl,
		arg.Document,
		arg.Comment,
		arg.FeedUrl,
		arg.SidecarRkey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
