// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: share_metadata.sql

package db

import (
	"context"
)

const getFeedEntryShareMetadataByDocument = `-- name: GetFeedEntryShareMetadataByDocument :one
SELECT title, entry_slug, url
FROM feed_entries
WHERE guid = ?
LIMIT 1
`

type GetFeedEntryShareMetadataByDocumentRow struct {
	Title     *string `json:"title"`
	EntrySlug string  `json:"entry_slug"`
	Url       string  `json:"url"`
}

func (q *Queries) GetFeedEntryShareMetadataByDocument(ctx context.Context, guid string) (GetFeedEntryShareMetadataByDocumentRow, error) {
	row := q.db.QueryRowContext(ctx, getFeedEntryShareMetadataByDocument, guid)
	var i GetFeedEntryShareMetadataByDocumentRow
	err := row.Scan(&i.Title, &i.EntrySlug, &i.Url)
	return i, err
}

const getFeedEntryShareMetadataByItemURL = `-- name: GetFeedEntryShareMetadataByItemURL :one
SELECT title, entry_slug, url
FROM feed_entries
WHERE url = ?
LIMIT 1
`

type GetFeedEntryShareMetadataByItemURLRow struct {
	Title     *string `json:"title"`
	EntrySlug string  `json:"entry_slug"`
	Url       string  `json:"url"`
}

func (q *Queries) GetFeedEntryShareMetadataByItemURL(ctx context.Context, url string) (GetFeedEntryShareMetadataByItemURLRow, error) {
	row := q.db.QueryRowContext(ctx, getFeedEntryShareMetadataByItemURL, url)
	var i GetFeedEntryShareMetadataByItemURLRow
	err := row.Scan(&i.Title, &i.EntrySlug, &i.Url)
	return i, err
}

const getShareMetadataCache = `-- name: GetShareMetadataCache :one
SELECT target_key, title, target_url, fetched_at, failure_count, next_retry_at
FROM share_metadata_cache
WHERE target_key = ?
`

func (q *Queries) GetShareMetadataCache(ctx context.Context, targetKey string) (ShareMetadataCache, error) {
	row := q.db.QueryRowContext(ctx, getShareMetadataCache, targetKey)
	var i ShareMetadataCache
	err := row.Scan(
		&i.TargetKey,
		&i.Title,
		&i.TargetUrl,
		&i.FetchedAt,
		&i.FailureCount,
		&i.NextRetryAt,
	)
	return i, err
}

const recordShareMetadataFailure = `-- name: RecordShareMetadataFailure :exec
INSERT INTO share_metadata_cache (
    target_key, title, target_url, fetched_at, failure_count, next_retry_at
) VALUES (?, NULL, NULL, NULL, ?, ?)
ON CONFLICT (target_key) DO UPDATE SET
    failure_count = excluded.failure_count,
    next_retry_at = excluded.next_retry_at
`

type RecordShareMetadataFailureParams struct {
	TargetKey    string  `json:"target_key"`
	FailureCount int64   `json:"failure_count"`
	NextRetryAt  *string `json:"next_retry_at"`
}

// Preserve the last successful payload so a transient failure serves stale metadata.
func (q *Queries) RecordShareMetadataFailure(ctx context.Context, arg RecordShareMetadataFailureParams) error {
	_, err := q.db.ExecContext(ctx, recordShareMetadataFailure, arg.TargetKey, arg.FailureCount, arg.NextRetryAt)
	return err
}

const upsertShareMetadataSuccess = `-- name: UpsertShareMetadataSuccess :exec
INSERT INTO share_metadata_cache (
    target_key, title, target_url, fetched_at, failure_count, next_retry_at
) VALUES (?, ?, ?, ?, 0, NULL)
ON CONFLICT (target_key) DO UPDATE SET
    title = excluded.title,
    target_url = excluded.target_url,
    fetched_at = excluded.fetched_at,
    failure_count = 0,
    next_retry_at = NULL
`

type UpsertShareMetadataSuccessParams struct {
	TargetKey string  `json:"target_key"`
	Title     *string `json:"title"`
	TargetUrl *string `json:"target_url"`
	FetchedAt *string `json:"fetched_at"`
}

func (q *Queries) UpsertShareMetadataSuccess(ctx context.Context, arg UpsertShareMetadataSuccessParams) error {
	_, err := q.db.ExecContext(ctx, upsertShareMetadataSuccess,
		arg.TargetKey,
		arg.Title,
		arg.TargetUrl,
		arg.FetchedAt,
	)
	return err
}
