// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package db

import (
	"context"
)

const deleteUserSubscription = `-- name: DeleteUserSubscription :exec
DELETE FROM user_subscriptions WHERE did = ? AND rkey = ?
`

type DeleteUserSubscriptionParams struct {
	Did  string `json:"did"`
	Rkey string `json:"rkey"`
}

func (q *Queries) DeleteUserSubscription(ctx context.Context, arg DeleteUserSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserSubscription, arg.Did, arg.Rkey)
	return err
}

const getFeed = `-- name: GetFeed :one
SELECT feed_url, site_url, etag, last_modified, last_fetched_at, created_at, updated_at
FROM feeds WHERE feed_url = ?
`

func (q *Queries) GetFeed(ctx context.Context, feedUrl string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeed, feedUrl)
	var i Feed
	err := row.Scan(
		&i.FeedUrl,
		&i.SiteUrl,
		&i.Etag,
		&i.LastModified,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSubscription = `-- name: GetUserSubscription :one
SELECT did, rkey, at_uri, feed_url, title, custom_title, custom_icon_url, created_at, updated_at
FROM user_subscriptions WHERE did = ? AND rkey = ?
`

type GetUserSubscriptionParams struct {
	Did  string `json:"did"`
	Rkey string `json:"rkey"`
}

func (q *Queries) GetUserSubscription(ctx context.Context, arg GetUserSubscriptionParams) (UserSubscription, error) {
	row := q.db.QueryRowContext(ctx, getUserSubscription, arg.Did, arg.Rkey)
	var i UserSubscription
	err := row.Scan(
		&i.Did,
		&i.Rkey,
		&i.AtUri,
		&i.FeedUrl,
		&i.Title,
		&i.CustomTitle,
		&i.CustomIconUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSubscriptionByFeedURL = `-- name: GetUserSubscriptionByFeedURL :one
SELECT did, rkey, at_uri, feed_url, title, custom_title, custom_icon_url, created_at, updated_at
FROM user_subscriptions WHERE did = ? AND feed_url = ?
`

type GetUserSubscriptionByFeedURLParams struct {
	Did     string `json:"did"`
	FeedUrl string `json:"feed_url"`
}

func (q *Queries) GetUserSubscriptionByFeedURL(ctx context.Context, arg GetUserSubscriptionByFeedURLParams) (UserSubscription, error) {
	row := q.db.QueryRowContext(ctx, getUserSubscriptionByFeedURL, arg.Did, arg.FeedUrl)
	var i UserSubscription
	err := row.Scan(
		&i.Did,
		&i.Rkey,
		&i.AtUri,
		&i.FeedUrl,
		&i.Title,
		&i.CustomTitle,
		&i.CustomIconUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserSubscriptions = `-- name: ListUserSubscriptions :many
SELECT did, rkey, at_uri, feed_url, title, custom_title, custom_icon_url, created_at, updated_at
FROM user_subscriptions WHERE did = ?
ORDER BY COALESCE(NULLIF(custom_title, ''), title, feed_url) COLLATE NOCASE ASC
`

func (q *Queries) ListUserSubscriptions(ctx context.Context, did string) ([]UserSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listUserSubscriptions, did)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSubscription
	for rows.Next() {
		var i UserSubscription
		if err := rows.Scan(
			&i.Did,
			&i.Rkey,
			&i.AtUri,
			&i.FeedUrl,
			&i.Title,
			&i.CustomTitle,
			&i.CustomIconUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeedFetchState = `-- name: UpdateFeedFetchState :exec
UPDATE feeds
SET etag = ?, last_modified = ?, last_fetched_at = ?, updated_at = ?
WHERE feed_url = ?
`

type UpdateFeedFetchStateParams struct {
	Etag          *string `json:"etag"`
	LastModified  *string `json:"last_modified"`
	LastFetchedAt *string `json:"last_fetched_at"`
	UpdatedAt     string  `json:"updated_at"`
	FeedUrl       string  `json:"feed_url"`
}

func (q *Queries) UpdateFeedFetchState(ctx context.Context, arg UpdateFeedFetchStateParams) error {
	_, err := q.db.ExecContext(ctx, updateFeedFetchState,
		arg.Etag,
		arg.LastModified,
		arg.LastFetchedAt,
		arg.UpdatedAt,
		arg.FeedUrl,
	)
	return err
}

const updateUserSubscriptionsTitleByFeedURL = `-- name: UpdateUserSubscriptionsTitleByFeedURL :exec
UPDATE user_subscriptions
SET title = ?, updated_at = ?
WHERE feed_url = ?
`

type UpdateUserSubscriptionsTitleByFeedURLParams struct {
	Title     *string `json:"title"`
	UpdatedAt string  `json:"updated_at"`
	FeedUrl   string  `json:"feed_url"`
}

func (q *Queries) UpdateUserSubscriptionsTitleByFeedURL(ctx context.Context, arg UpdateUserSubscriptionsTitleByFeedURLParams) error {
	_, err := q.db.ExecContext(ctx, updateUserSubscriptionsTitleByFeedURL, arg.Title, arg.UpdatedAt, arg.FeedUrl)
	return err
}

const upsertFeed = `-- name: UpsertFeed :exec
INSERT INTO feeds (feed_url, site_url, created_at, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (feed_url) DO UPDATE SET
    site_url = COALESCE(NULLIF(excluded.site_url, ''), feeds.site_url),
    updated_at = excluded.updated_at
`

type UpsertFeedParams struct {
	FeedUrl   string  `json:"feed_url"`
	SiteUrl   *string `json:"site_url"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
}

func (q *Queries) UpsertFeed(ctx context.Context, arg UpsertFeedParams) error {
	_, err := q.db.ExecContext(ctx, upsertFeed,
		arg.FeedUrl,
		arg.SiteUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertUserSubscription = `-- name: UpsertUserSubscription :exec
INSERT INTO user_subscriptions (
    did, rkey, at_uri, feed_url, title, custom_title, custom_icon_url, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (did, rkey) DO UPDATE SET
    at_uri          = excluded.at_uri,
    feed_url        = excluded.feed_url,
    title           = excluded.title,
    custom_title    = excluded.custom_title,
    custom_icon_url = excluded.custom_icon_url,
    updated_at      = excluded.updated_at
`

type UpsertUserSubscriptionParams struct {
	Did           string  `json:"did"`
	Rkey          string  `json:"rkey"`
	AtUri         string  `json:"at_uri"`
	FeedUrl       string  `json:"feed_url"`
	Title         *string `json:"title"`
	CustomTitle   *string `json:"custom_title"`
	CustomIconUrl *string `json:"custom_icon_url"`
	CreatedAt     string  `json:"created_at"`
	UpdatedAt     string  `json:"updated_at"`
}

func (q *Queries) UpsertUserSubscription(ctx context.Context, arg UpsertUserSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserSubscription,
		arg.Did,
		arg.Rkey,
		arg.AtUri,
		arg.FeedUrl,
		arg.Title,
		arg.CustomTitle,
		arg.CustomIconUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
