// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package db

import (
	"context"
)

const deleteUserSubscription = `-- name: DeleteUserSubscription :exec
DELETE FROM user_subscriptions WHERE did = ? AND rkey = ?
`

type DeleteUserSubscriptionParams struct {
	Did  string `json:"did"`
	Rkey string `json:"rkey"`
}

func (q *Queries) DeleteUserSubscription(ctx context.Context, arg DeleteUserSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserSubscription, arg.Did, arg.Rkey)
	return err
}

const getFeed = `-- name: GetFeed :one
SELECT feed_url, site_url, etag, last_modified, last_fetched_at, icon_url, icon_fetched_at, created_at, updated_at
FROM feeds WHERE feed_url = ?
`

func (q *Queries) GetFeed(ctx context.Context, feedUrl string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeed, feedUrl)
	var i Feed
	err := row.Scan(
		&i.FeedUrl,
		&i.SiteUrl,
		&i.Etag,
		&i.LastModified,
		&i.LastFetchedAt,
		&i.IconUrl,
		&i.IconFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeedIconURL = `-- name: GetFeedIconURL :one
SELECT icon_url FROM feeds WHERE feed_url = ?
`

// Returns the stored icon URL for a feed. Drives the favicon-proxy SSRF guard:
// the proxy only streams URLs the sync pipeline has already vetted.
func (q *Queries) GetFeedIconURL(ctx context.Context, feedUrl string) (*string, error) {
	row := q.db.QueryRowContext(ctx, getFeedIconURL, feedUrl)
	var icon_url *string
	err := row.Scan(&icon_url)
	return icon_url, err
}

const getUserSourceWithStats = `-- name: GetUserSourceWithStats :one
SELECT
    us.did, us.rkey, us.at_uri, us.feed_url, us.title,
    us.created_at, us.updated_at,
    f.site_url, f.icon_url,
    COALESCE((SELECT MAX(published_at) FROM feed_entries fe WHERE fe.feed_url = us.feed_url), '') AS last_published_at,
    COALESCE((SELECT MIN(published_at) FROM feed_entries fe WHERE fe.feed_url = us.feed_url), '') AS first_published_at,
    (SELECT COUNT(*) FROM feed_entries fe WHERE fe.feed_url = us.feed_url AND fe.published_at >= ?1 AND fe.published_at < ?2) AS count_7d,
    (SELECT COUNT(*) FROM feed_entries fe WHERE fe.feed_url = us.feed_url AND fe.published_at >= ?3 AND fe.published_at < ?2) AS count_28d,
    (SELECT COUNT(*) FROM feed_entries fe WHERE fe.feed_url = us.feed_url AND fe.published_at >= ?4 AND fe.published_at < ?2) AS count_56d,
    (SELECT COUNT(*) FROM feed_entries fe WHERE fe.feed_url = us.feed_url AND fe.published_at >= ?5 AND fe.published_at < ?2) AS count_84d,
    (SELECT COUNT(*) FROM feed_entries fe WHERE fe.feed_url = us.feed_url) AS total_entries,
    (SELECT COUNT(*) FROM user_saves s WHERE s.did = us.did AND s.feed_url = us.feed_url) AS saved_by_you
FROM user_subscriptions us
LEFT JOIN feeds f ON f.feed_url = us.feed_url
WHERE us.did = ?6 AND us.rkey = ?7
`

type GetUserSourceWithStatsParams struct {
	Cutoff7d  string `json:"cutoff_7d"`
	Now       string `json:"now"`
	Cutoff28d string `json:"cutoff_28d"`
	Cutoff56d string `json:"cutoff_56d"`
	Cutoff84d string `json:"cutoff_84d"`
	Did       string `json:"did"`
	Rkey      string `json:"rkey"`
}

type GetUserSourceWithStatsRow struct {
	Did              string      `json:"did"`
	Rkey             string      `json:"rkey"`
	AtUri            string      `json:"at_uri"`
	FeedUrl          string      `json:"feed_url"`
	Title            *string     `json:"title"`
	CreatedAt        string      `json:"created_at"`
	UpdatedAt        string      `json:"updated_at"`
	SiteUrl          *string     `json:"site_url"`
	IconUrl          *string     `json:"icon_url"`
	LastPublishedAt  interface{} `json:"last_published_at"`
	FirstPublishedAt interface{} `json:"first_published_at"`
	Count7d          int64       `json:"count_7d"`
	Count28d         int64       `json:"count_28d"`
	Count56d         int64       `json:"count_56d"`
	Count84d         int64       `json:"count_84d"`
	TotalEntries     int64       `json:"total_entries"`
	SavedByYou       int64       `json:"saved_by_you"`
}

// Single-source counterpart to ListUserSourcesWithStats, keyed by (did, rkey).
// Carries the same windowed counts plus total_entries and saved_by_you so the
// source detail page can render its stat row in one query.
func (q *Queries) GetUserSourceWithStats(ctx context.Context, arg GetUserSourceWithStatsParams) (GetUserSourceWithStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserSourceWithStats,
		arg.Cutoff7d,
		arg.Now,
		arg.Cutoff28d,
		arg.Cutoff56d,
		arg.Cutoff84d,
		arg.Did,
		arg.Rkey,
	)
	var i GetUserSourceWithStatsRow
	err := row.Scan(
		&i.Did,
		&i.Rkey,
		&i.AtUri,
		&i.FeedUrl,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SiteUrl,
		&i.IconUrl,
		&i.LastPublishedAt,
		&i.FirstPublishedAt,
		&i.Count7d,
		&i.Count28d,
		&i.Count56d,
		&i.Count84d,
		&i.TotalEntries,
		&i.SavedByYou,
	)
	return i, err
}

const getUserSubscription = `-- name: GetUserSubscription :one
SELECT did, rkey, at_uri, feed_url, title, created_at, updated_at
FROM user_subscriptions WHERE did = ? AND rkey = ?
`

type GetUserSubscriptionParams struct {
	Did  string `json:"did"`
	Rkey string `json:"rkey"`
}

func (q *Queries) GetUserSubscription(ctx context.Context, arg GetUserSubscriptionParams) (UserSubscription, error) {
	row := q.db.QueryRowContext(ctx, getUserSubscription, arg.Did, arg.Rkey)
	var i UserSubscription
	err := row.Scan(
		&i.Did,
		&i.Rkey,
		&i.AtUri,
		&i.FeedUrl,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSubscriptionByFeedURL = `-- name: GetUserSubscriptionByFeedURL :one
SELECT did, rkey, at_uri, feed_url, title, created_at, updated_at
FROM user_subscriptions WHERE did = ? AND feed_url = ?
`

type GetUserSubscriptionByFeedURLParams struct {
	Did     string `json:"did"`
	FeedUrl string `json:"feed_url"`
}

func (q *Queries) GetUserSubscriptionByFeedURL(ctx context.Context, arg GetUserSubscriptionByFeedURLParams) (UserSubscription, error) {
	row := q.db.QueryRowContext(ctx, getUserSubscriptionByFeedURL, arg.Did, arg.FeedUrl)
	var i UserSubscription
	err := row.Scan(
		&i.Did,
		&i.Rkey,
		&i.AtUri,
		&i.FeedUrl,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserSourcesWithStats = `-- name: ListUserSourcesWithStats :many
SELECT
    us.did, us.rkey, us.at_uri, us.feed_url, us.title,
    us.created_at, us.updated_at,
    f.site_url, f.icon_url,
    COALESCE((SELECT MAX(published_at) FROM feed_entries fe WHERE fe.feed_url = us.feed_url), '') AS last_published_at,
    COALESCE((SELECT MIN(published_at) FROM feed_entries fe WHERE fe.feed_url = us.feed_url), '') AS first_published_at,
    (SELECT COUNT(*) FROM feed_entries fe WHERE fe.feed_url = us.feed_url AND fe.published_at >= ?1 AND fe.published_at < ?2) AS count_7d,
    (SELECT COUNT(*) FROM feed_entries fe WHERE fe.feed_url = us.feed_url AND fe.published_at >= ?3 AND fe.published_at < ?2) AS count_28d,
    (SELECT COUNT(*) FROM feed_entries fe WHERE fe.feed_url = us.feed_url AND fe.published_at >= ?4 AND fe.published_at < ?2) AS count_56d,
    (SELECT COUNT(*) FROM feed_entries fe WHERE fe.feed_url = us.feed_url AND fe.published_at >= ?5 AND fe.published_at < ?2) AS count_84d
FROM user_subscriptions us
LEFT JOIN feeds f ON f.feed_url = us.feed_url
WHERE us.did = ?6
ORDER BY COALESCE(NULLIF(us.title, ''), us.feed_url) COLLATE NOCASE ASC
`

type ListUserSourcesWithStatsParams struct {
	Cutoff7d  string `json:"cutoff_7d"`
	Now       string `json:"now"`
	Cutoff28d string `json:"cutoff_28d"`
	Cutoff56d string `json:"cutoff_56d"`
	Cutoff84d string `json:"cutoff_84d"`
	Did       string `json:"did"`
}

type ListUserSourcesWithStatsRow struct {
	Did              string      `json:"did"`
	Rkey             string      `json:"rkey"`
	AtUri            string      `json:"at_uri"`
	FeedUrl          string      `json:"feed_url"`
	Title            *string     `json:"title"`
	CreatedAt        string      `json:"created_at"`
	UpdatedAt        string      `json:"updated_at"`
	SiteUrl          *string     `json:"site_url"`
	IconUrl          *string     `json:"icon_url"`
	LastPublishedAt  interface{} `json:"last_published_at"`
	FirstPublishedAt interface{} `json:"first_published_at"`
	Count7d          int64       `json:"count_7d"`
	Count28d         int64       `json:"count_28d"`
	Count56d         int64       `json:"count_56d"`
	Count84d         int64       `json:"count_84d"`
}

// One row per subscription with feed metadata and windowed entry stats. The
// four window cutoffs (7d, 28d, 56d, 84d as ISO timestamps) and "now" are
// passed in by the handler so all rows share a single clock.
func (q *Queries) ListUserSourcesWithStats(ctx context.Context, arg ListUserSourcesWithStatsParams) ([]ListUserSourcesWithStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserSourcesWithStats,
		arg.Cutoff7d,
		arg.Now,
		arg.Cutoff28d,
		arg.Cutoff56d,
		arg.Cutoff84d,
		arg.Did,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSourcesWithStatsRow
	for rows.Next() {
		var i ListUserSourcesWithStatsRow
		if err := rows.Scan(
			&i.Did,
			&i.Rkey,
			&i.AtUri,
			&i.FeedUrl,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SiteUrl,
			&i.IconUrl,
			&i.LastPublishedAt,
			&i.FirstPublishedAt,
			&i.Count7d,
			&i.Count28d,
			&i.Count56d,
			&i.Count84d,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSubscriptions = `-- name: ListUserSubscriptions :many
SELECT did, rkey, at_uri, feed_url, title, created_at, updated_at
FROM user_subscriptions WHERE did = ?
ORDER BY COALESCE(NULLIF(title, ''), feed_url) COLLATE NOCASE ASC
`

func (q *Queries) ListUserSubscriptions(ctx context.Context, did string) ([]UserSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listUserSubscriptions, did)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSubscription
	for rows.Next() {
		var i UserSubscription
		if err := rows.Scan(
			&i.Did,
			&i.Rkey,
			&i.AtUri,
			&i.FeedUrl,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFeedIconURL = `-- name: SetFeedIconURL :exec
UPDATE feeds
SET icon_url = ?, icon_fetched_at = ?, updated_at = ?
WHERE feed_url = ?
`

type SetFeedIconURLParams struct {
	IconUrl       *string `json:"icon_url"`
	IconFetchedAt *string `json:"icon_fetched_at"`
	UpdatedAt     string  `json:"updated_at"`
	FeedUrl       string  `json:"feed_url"`
}

func (q *Queries) SetFeedIconURL(ctx context.Context, arg SetFeedIconURLParams) error {
	_, err := q.db.ExecContext(ctx, setFeedIconURL,
		arg.IconUrl,
		arg.IconFetchedAt,
		arg.UpdatedAt,
		arg.FeedUrl,
	)
	return err
}

const updateFeedFetchState = `-- name: UpdateFeedFetchState :exec
UPDATE feeds
SET etag = ?, last_modified = ?, last_fetched_at = ?, updated_at = ?
WHERE feed_url = ?
`

type UpdateFeedFetchStateParams struct {
	Etag          *string `json:"etag"`
	LastModified  *string `json:"last_modified"`
	LastFetchedAt *string `json:"last_fetched_at"`
	UpdatedAt     string  `json:"updated_at"`
	FeedUrl       string  `json:"feed_url"`
}

func (q *Queries) UpdateFeedFetchState(ctx context.Context, arg UpdateFeedFetchStateParams) error {
	_, err := q.db.ExecContext(ctx, updateFeedFetchState,
		arg.Etag,
		arg.LastModified,
		arg.LastFetchedAt,
		arg.UpdatedAt,
		arg.FeedUrl,
	)
	return err
}

const upsertFeed = `-- name: UpsertFeed :exec
INSERT INTO feeds (feed_url, site_url, created_at, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (feed_url) DO UPDATE SET
    site_url = COALESCE(NULLIF(excluded.site_url, ''), feeds.site_url),
    updated_at = excluded.updated_at
`

type UpsertFeedParams struct {
	FeedUrl   string  `json:"feed_url"`
	SiteUrl   *string `json:"site_url"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
}

func (q *Queries) UpsertFeed(ctx context.Context, arg UpsertFeedParams) error {
	_, err := q.db.ExecContext(ctx, upsertFeed,
		arg.FeedUrl,
		arg.SiteUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertUserSubscription = `-- name: UpsertUserSubscription :exec
INSERT INTO user_subscriptions (
    did, rkey, at_uri, feed_url, title, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (did, rkey) DO UPDATE SET
    at_uri     = excluded.at_uri,
    feed_url   = excluded.feed_url,
    title      = excluded.title,
    updated_at = excluded.updated_at
`

type UpsertUserSubscriptionParams struct {
	Did       string  `json:"did"`
	Rkey      string  `json:"rkey"`
	AtUri     string  `json:"at_uri"`
	FeedUrl   string  `json:"feed_url"`
	Title     *string `json:"title"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
}

func (q *Queries) UpsertUserSubscription(ctx context.Context, arg UpsertUserSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserSubscription,
		arg.Did,
		arg.Rkey,
		arg.AtUri,
		arg.FeedUrl,
		arg.Title,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
