// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package db

import (
	"context"
)

const listAllFeedURLs = `-- name: ListAllFeedURLs :many
SELECT feed_url FROM feeds ORDER BY feed_url
`

func (q *Queries) ListAllFeedURLs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAllFeedURLs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var feed_url string
		if err := rows.Scan(&feed_url); err != nil {
			return nil, err
		}
		items = append(items, feed_url)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedURLsForUser = `-- name: ListFeedURLsForUser :many
SELECT feed_url FROM user_subscriptions WHERE did = ?
`

func (q *Queries) ListFeedURLsForUser(ctx context.Context, did string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listFeedURLsForUser, did)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var feed_url string
		if err := rows.Scan(&feed_url); err != nil {
			return nil, err
		}
		items = append(items, feed_url)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSubscriptionsForSync = `-- name: ListUserSubscriptionsForSync :many
SELECT did, rkey, at_uri, feed_url, kind, sidecar_rkey, title, is_primary, tags, created_at, updated_at
FROM user_subscriptions
WHERE did = ?
`

func (q *Queries) ListUserSubscriptionsForSync(ctx context.Context, did string) ([]UserSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listUserSubscriptionsForSync, did)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSubscription
	for rows.Next() {
		var i UserSubscription
		if err := rows.Scan(
			&i.Did,
			&i.Rkey,
			&i.AtUri,
			&i.FeedUrl,
			&i.Kind,
			&i.SidecarRkey,
			&i.Title,
			&i.IsPrimary,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
