// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tap.sql

package db

import (
	"context"
)

const deleteTapDirtyRepo = `-- name: DeleteTapDirtyRepo :exec
DELETE FROM tap_dirty_repos WHERE did = ? AND marked_at <= ?
`

type DeleteTapDirtyRepoParams struct {
	Did      string `json:"did"`
	MarkedAt string `json:"marked_at"`
}

// The marked_at guard clears only the mark the rebuild actually consumed: a
// repo re-dirtied while its rebuild was running keeps a newer row and gets
// rebuilt again, instead of having that change silently dropped.
func (q *Queries) DeleteTapDirtyRepo(ctx context.Context, arg DeleteTapDirtyRepoParams) error {
	_, err := q.db.ExecContext(ctx, deleteTapDirtyRepo, arg.Did, arg.MarkedAt)
	return err
}

const deleteTapRecord = `-- name: DeleteTapRecord :exec
DELETE FROM tap_records WHERE did = ? AND collection = ? AND rkey = ?
`

type DeleteTapRecordParams struct {
	Did        string `json:"did"`
	Collection string `json:"collection"`
	Rkey       string `json:"rkey"`
}

func (q *Queries) DeleteTapRecord(ctx context.Context, arg DeleteTapRecordParams) error {
	_, err := q.db.ExecContext(ctx, deleteTapRecord, arg.Did, arg.Collection, arg.Rkey)
	return err
}

const deleteTapRecordsForRepo = `-- name: DeleteTapRecordsForRepo :exec
DELETE FROM tap_records WHERE did = ?
`

func (q *Queries) DeleteTapRecordsForRepo(ctx context.Context, did string) error {
	_, err := q.db.ExecContext(ctx, deleteTapRecordsForRepo, did)
	return err
}

const insertTapSeededDid = `-- name: InsertTapSeededDid :exec
INSERT INTO tap_seeder_state (did, seeded_at) VALUES (?, ?)
ON CONFLICT (did) DO NOTHING
`

type InsertTapSeededDidParams struct {
	Did      string `json:"did"`
	SeededAt string `json:"seeded_at"`
}

// DO NOTHING keeps seeded_at at the first successful backfill, so a re-run
// never rewrites the stamp it is meant to check.
func (q *Queries) InsertTapSeededDid(ctx context.Context, arg InsertTapSeededDidParams) error {
	_, err := q.db.ExecContext(ctx, insertTapSeededDid, arg.Did, arg.SeededAt)
	return err
}

const listTapDirtyRepos = `-- name: ListTapDirtyRepos :many
SELECT did, marked_at FROM tap_dirty_repos ORDER BY marked_at, did LIMIT ?
`

// Oldest mark first so a backlog drains in arrival order. marked_at rides
// along because DeleteTapDirtyRepo needs the value that was read.
func (q *Queries) ListTapDirtyRepos(ctx context.Context, limit int64) ([]TapDirtyRepo, error) {
	rows, err := q.db.QueryContext(ctx, listTapDirtyRepos, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TapDirtyRepo
	for rows.Next() {
		var i TapDirtyRepo
		if err := rows.Scan(&i.Did, &i.MarkedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTapRecordsForRepo = `-- name: ListTapRecordsForRepo :many
SELECT did, collection, rkey, cid, record, indexed_at
FROM tap_records WHERE did = ?
`

func (q *Queries) ListTapRecordsForRepo(ctx context.Context, did string) ([]TapRecord, error) {
	rows, err := q.db.QueryContext(ctx, listTapRecordsForRepo, did)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TapRecord
	for rows.Next() {
		var i TapRecord
		if err := rows.Scan(
			&i.Did,
			&i.Collection,
			&i.Rkey,
			&i.Cid,
			&i.Record,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTapSeededDids = `-- name: ListTapSeededDids :many
SELECT did FROM tap_seeder_state
`

func (q *Queries) ListTapSeededDids(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTapSeededDids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var did string
		if err := rows.Scan(&did); err != nil {
			return nil, err
		}
		items = append(items, did)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTapRepoDirty = `-- name: MarkTapRepoDirty :exec
INSERT INTO tap_dirty_repos (did, marked_at) VALUES (?, ?)
ON CONFLICT (did) DO UPDATE SET marked_at = excluded.marked_at
`

type MarkTapRepoDirtyParams struct {
	Did      string `json:"did"`
	MarkedAt string `json:"marked_at"`
}

func (q *Queries) MarkTapRepoDirty(ctx context.Context, arg MarkTapRepoDirtyParams) error {
	_, err := q.db.ExecContext(ctx, markTapRepoDirty, arg.Did, arg.MarkedAt)
	return err
}

const upsertTapRecord = `-- name: UpsertTapRecord :exec
INSERT INTO tap_records (did, collection, rkey, cid, record, indexed_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (did, collection, rkey) DO UPDATE SET
    cid        = excluded.cid,
    record     = excluded.record,
    indexed_at = excluded.indexed_at
`

type UpsertTapRecordParams struct {
	Did        string `json:"did"`
	Collection string `json:"collection"`
	Rkey       string `json:"rkey"`
	Cid        string `json:"cid"`
	Record     string `json:"record"`
	IndexedAt  string `json:"indexed_at"`
}

func (q *Queries) UpsertTapRecord(ctx context.Context, arg UpsertTapRecordParams) error {
	_, err := q.db.ExecContext(ctx, upsertTapRecord,
		arg.Did,
		arg.Collection,
		arg.Rkey,
		arg.Cid,
		arg.Record,
		arg.IndexedAt,
	)
	return err
}
