// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tap.sql

package db

import (
	"context"
)

const deleteTapDirtyRepo = `-- name: DeleteTapDirtyRepo :exec
DELETE FROM tap_dirty_repos WHERE did = ? AND marked_seq = ?
`

type DeleteTapDirtyRepoParams struct {
	Did       string `json:"did"`
	MarkedSeq int64  `json:"marked_seq"`
}

func (q *Queries) DeleteTapDirtyRepo(ctx context.Context, arg DeleteTapDirtyRepoParams) error {
	_, err := q.db.ExecContext(ctx, deleteTapDirtyRepo, arg.Did, arg.MarkedSeq)
	return err
}

const deleteTapRecord = `-- name: DeleteTapRecord :exec
DELETE FROM tap_records WHERE did = ? AND collection = ? AND rkey = ?
`

type DeleteTapRecordParams struct {
	Did        string `json:"did"`
	Collection string `json:"collection"`
	Rkey       string `json:"rkey"`
}

func (q *Queries) DeleteTapRecord(ctx context.Context, arg DeleteTapRecordParams) error {
	_, err := q.db.ExecContext(ctx, deleteTapRecord, arg.Did, arg.Collection, arg.Rkey)
	return err
}

const deleteTapRecordsForRepo = `-- name: DeleteTapRecordsForRepo :exec
DELETE FROM tap_records WHERE did = ?
`

func (q *Queries) DeleteTapRecordsForRepo(ctx context.Context, did string) error {
	_, err := q.db.ExecContext(ctx, deleteTapRecordsForRepo, did)
	return err
}

const getTapRepoState = `-- name: GetTapRepoState :one
SELECT did, handle, is_active, status, updated_at
FROM tap_repo_states
WHERE did = ?
`

func (q *Queries) GetTapRepoState(ctx context.Context, did string) (TapRepoState, error) {
	row := q.db.QueryRowContext(ctx, getTapRepoState, did)
	var i TapRepoState
	err := row.Scan(
		&i.Did,
		&i.Handle,
		&i.IsActive,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const listTapDirtyRepos = `-- name: ListTapDirtyRepos :many
SELECT did, marked_seq FROM tap_dirty_repos ORDER BY marked_seq, did LIMIT ?
`

func (q *Queries) ListTapDirtyRepos(ctx context.Context, limit int64) ([]TapDirtyRepo, error) {
	rows, err := q.db.QueryContext(ctx, listTapDirtyRepos, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TapDirtyRepo
	for rows.Next() {
		var i TapDirtyRepo
		if err := rows.Scan(&i.Did, &i.MarkedSeq); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTapRecordsForRepo = `-- name: ListTapRecordsForRepo :many
SELECT did, collection, rkey, cid, record, indexed_at
FROM tap_records WHERE did = ?
`

func (q *Queries) ListTapRecordsForRepo(ctx context.Context, did string) ([]TapRecord, error) {
	rows, err := q.db.QueryContext(ctx, listTapRecordsForRepo, did)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TapRecord
	for rows.Next() {
		var i TapRecord
		if err := rows.Scan(
			&i.Did,
			&i.Collection,
			&i.Rkey,
			&i.Cid,
			&i.Record,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTapRepoDirty = `-- name: MarkTapRepoDirty :exec
INSERT INTO tap_dirty_repos (did, marked_seq) VALUES (?, ?)
ON CONFLICT (did) DO UPDATE SET marked_seq = MAX(tap_dirty_repos.marked_seq, excluded.marked_seq)
`

type MarkTapRepoDirtyParams struct {
	Did       string `json:"did"`
	MarkedSeq int64  `json:"marked_seq"`
}

func (q *Queries) MarkTapRepoDirty(ctx context.Context, arg MarkTapRepoDirtyParams) error {
	_, err := q.db.ExecContext(ctx, markTapRepoDirty, arg.Did, arg.MarkedSeq)
	return err
}

const tapRepoIsMirrored = `-- name: TapRepoIsMirrored :one
SELECT EXISTS (
    SELECT 1 FROM tap_records r WHERE r.did = ?1
    UNION ALL
    SELECT 1 FROM tap_repo_states s WHERE s.did = ?1
) AS mirrored
`

// Existence probe for the network-wide identity/account/sync stream. Those
// markers reach every subscriber regardless of the collection filter, so a
// marker for a repo we never mirrored must not mint state rows for it.
func (q *Queries) TapRepoIsMirrored(ctx context.Context, did string) (bool, error) {
	row := q.db.QueryRowContext(ctx, tapRepoIsMirrored, did)
	var mirrored bool
	err := row.Scan(&mirrored)
	return mirrored, err
}

const upsertTapRecord = `-- name: UpsertTapRecord :exec
INSERT INTO tap_records (did, collection, rkey, cid, record, indexed_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (did, collection, rkey) DO UPDATE SET
    cid        = excluded.cid,
    record     = excluded.record,
    indexed_at = excluded.indexed_at
`

type UpsertTapRecordParams struct {
	Did        string `json:"did"`
	Collection string `json:"collection"`
	Rkey       string `json:"rkey"`
	Cid        string `json:"cid"`
	Record     string `json:"record"`
	IndexedAt  string `json:"indexed_at"`
}

func (q *Queries) UpsertTapRecord(ctx context.Context, arg UpsertTapRecordParams) error {
	_, err := q.db.ExecContext(ctx, upsertTapRecord,
		arg.Did,
		arg.Collection,
		arg.Rkey,
		arg.Cid,
		arg.Record,
		arg.IndexedAt,
	)
	return err
}

const upsertTapRepoAccount = `-- name: UpsertTapRepoAccount :exec
INSERT INTO tap_repo_states (did, handle, is_active, status, updated_at)
VALUES (?, '', ?, ?, ?)
ON CONFLICT (did) DO UPDATE SET
    is_active  = excluded.is_active,
    status     = excluded.status,
    updated_at = excluded.updated_at
`

type UpsertTapRepoAccountParams struct {
	Did       string `json:"did"`
	IsActive  int64  `json:"is_active"`
	Status    string `json:"status"`
	UpdatedAt string `json:"updated_at"`
}

// Status-only upsert. An account event carries no handle, so an existing row
// keeps the handle identity last resolved instead of blanking it.
func (q *Queries) UpsertTapRepoAccount(ctx context.Context, arg UpsertTapRepoAccountParams) error {
	_, err := q.db.ExecContext(ctx, upsertTapRepoAccount,
		arg.Did,
		arg.IsActive,
		arg.Status,
		arg.UpdatedAt,
	)
	return err
}

const upsertTapRepoHandle = `-- name: UpsertTapRepoHandle :exec
INSERT INTO tap_repo_states (did, handle, is_active, status, updated_at)
VALUES (?, ?, 1, '', ?)
ON CONFLICT (did) DO UPDATE SET
    handle     = excluded.handle,
    updated_at = excluded.updated_at
`

type UpsertTapRepoHandleParams struct {
	Did       string `json:"did"`
	Handle    string `json:"handle"`
	UpdatedAt string `json:"updated_at"`
}

// Handle-only upsert. An identity event carries no hosting status, so an
// existing row keeps whatever the account stream last said; a brand new row
// defaults to active, which is what a repo emitting identity events is.
func (q *Queries) UpsertTapRepoHandle(ctx context.Context, arg UpsertTapRepoHandleParams) error {
	_, err := q.db.ExecContext(ctx, upsertTapRepoHandle, arg.Did, arg.Handle, arg.UpdatedAt)
	return err
}

const upsertTapRepoState = `-- name: UpsertTapRepoState :exec
INSERT INTO tap_repo_states (did, handle, is_active, status, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (did) DO UPDATE SET
    handle     = excluded.handle,
    is_active  = excluded.is_active,
    status     = excluded.status,
    updated_at = excluded.updated_at
`

type UpsertTapRepoStateParams struct {
	Did       string `json:"did"`
	Handle    string `json:"handle"`
	IsActive  int64  `json:"is_active"`
	Status    string `json:"status"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) UpsertTapRepoState(ctx context.Context, arg UpsertTapRepoStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertTapRepoState,
		arg.Did,
		arg.Handle,
		arg.IsActive,
		arg.Status,
		arg.UpdatedAt,
	)
	return err
}
